// EVERY AXIS IS REACHABLE FROM AN AUTHORED VALUE, and every guard survives it.
//
// This is the wiring layer, which is where this repo has recorded twelve
// features shipping dead — each one correct at both ends with one hop cut. A
// validator that accepts a hover state and an emitter that never reads it are
// indistinguishable from outside: the build succeeds, the site publishes, and
// the customer is told the look was applied.
import test from "node:test";
import assert from "node:assert/strict";
import * as T from "../builder/site-theme.mjs";
import { normalizeSeeds } from "../builder/site-seeds.mjs";
import { AXES } from "../builder/site-style.mjs";
import { readAuthoredAxis, AXIS_DECLS, AXIS_RAMPS } from "../builder/site-authored.mjs";

const SEEDS = { name: "t", paper: "#f3ead8", ink: "#3a3530", accent: "#c47a58" };
const theme = normalizeSeeds(SEEDS).theme;
const BARE = T.themeCss(theme);

/**
 * ONE VALID ANSWER PER AXIS, hand-written because a generated one would be
 * generated by the same rules it is meant to test.
 *
 * THE LIST ITSELF IS NOT TRUSTED — the first test below requires it to cover
 * every axis the engine has, in both directions. A hand list is exactly what
 * leaves the twenty-fourth axis unreached while every assertion below passes.
 */
const AUTHORED = {
  corner: "border-radius: 14px",
  shadow: "box-shadow: 3px 3px 0 oklch(0 0 0 / 0.8)",
  buttons: "border-radius: 2px",
  inputs: "border-width: 3px",
  display: "color: oklch(0.5 0.2 20)",
  surface: "backdrop-filter: blur(9px)",
  skin: "transform: rotate(-1deg)",
  ambient: "animation-duration: 44s",
  hover: "transform: translateY(-5px)",
  pressed: "transform: scale(0.97)",
  focus: "outline-width: 4px",
  reveal: "opacity: 0; transform: translateY(22px)",
  transition: "opacity: 0; transform: translateY(9px)",
  scrim: "background-color: oklch(0.1 0.03 250 / 0.85)",
  selection: "background-color: oklch(0.6 0.2 300); color: oklch(1 0 0)",
  controls: "accent-color: oklch(0.55 0.18 150)",
  imagery: "filter: grayscale(0.6)",
  link: "color: oklch(0.45 0.19 265)",
  backdrop: { light: ["linear-gradient(#fff5,#0000)"], dark: ["linear-gradient(#0005,#0000)"] },
  decor: {
    light: ["repeating-linear-gradient(45deg,#0001 0 9px,transparent 9px 22px)"],
    dark: ["repeating-linear-gradient(45deg,#fff1 0 9px,transparent 9px 22px)"],
  },
  scale: { ratio: 1.42 },
  width: { ratio: 1.3 },
  tracking: { steps: [-0.03, -0.01, 0, 0.02, 0.04, 0.09] },
  leading: { steps: [1.05, 1.22, 1.44, 1.66] },
  weight: { steps: [150, 250, 350, 550, 750, 825, 900] },
  density: { spacing: 0.37 },
  border: { width: 3 },
  icon: { width: 2.75 },
  motion: { ms: 333, ease: "ease-in-out" },
};

/** The authored value in the shape the emitters read, via the real validator. */
function applied(axis) {
  const r = readAuthoredAxis(axis, AUTHORED[axis]);
  assert.equal(r.ok, true, axis + " was refused by its own validator: " + r.why);
  return { ...theme, [axis]: r.css ? { css: r.css } : (r.layers ? { layers: r.layers } : r.value) };
}
const cssFor = (axis) => T.themeCss(applied(axis));

// ─────────────────────────────────────────────────────────────────────────────

test("the fixture covers every axis the engine has, both ways", () => {
  // Or the sweep below runs over the ones somebody remembered.
  assert.deepEqual(Object.keys(AUTHORED).sort(), Object.keys(AXES).sort());
});

test("EVERY axis moves the stylesheet when it is authored", () => {
  // THE DEAD-AXIS GUARD, on the authored path. Its named twin already exists and
  // exists because `display` was stored, reported as applied, and changed
  // nothing for as long as it lived — it named `.font-heading`, a class no file
  // in the kit or the corpus carries.
  const dead = Object.keys(AUTHORED).filter((a) => cssFor(a) === BARE);
  assert.deepEqual(dead, [], "authored and changed nothing: " + dead.join(", "));
});

test("a NAMED value still works exactly as it did", () => {
  // Every site published before today carries names. A helper that took the
  // authored branch on a string would re-style the whole platform on one deploy.
  for (const [axis, spec] of Object.entries(AXES)) {
    for (const name of Object.keys(spec.options)) {
      assert.doesNotThrow(() => T.themeCss({ ...theme, [axis]: name }), axis + ": " + name);
    }
  }
  // And a name still reaches its own emitter rather than falling to the default.
  assert.notEqual(T.themeCss({ ...theme, icon: "heavy" }), BARE);
  assert.match(T.themeCss({ ...theme, icon: "heavy" }), /stroke-width: 2\.5/);
});

test("an axis the theme never set is still absent", () => {
  // The fallback that keeps a site which authored nothing byte-identical.
  assert.equal(T.themeCss({ ...theme, hover: undefined }), BARE);
  assert.equal(T.themeCss({ ...theme, hover: "none" }), BARE);
});

test("a prototype key is not an option", () => {
  // `MOTIONS["constructor"]` is a function — truthy, so it walks past a `??`
  // and hands back something that is not an option. `motionCss` guarded against
  // exactly this and would have lost the guard to a shared helper that did not.
  for (const axis of Object.keys(AXES)) {
    for (const key of ["constructor", "__proto__", "toString", "hasOwnProperty"]) {
      assert.doesNotThrow(() => T.themeCss({ ...theme, [axis]: key }), axis + " threw on " + key);
    }
  }
  assert.equal(T.themeCss({ ...theme, motion: "constructor" }), BARE,
    "a prototype key set a real axis");
});

// ─────────────────────────────────────────────────────────────────────────────
// THE GUARDS. Each is a rule the model must NOT be able to drop, because each
// failure is invisible on the machine that publishes the site.

test("hover keeps @media (hover: hover) — a tap must not stick", () => {
  // On a touch screen `:hover` STICKS after a tap, so without the query a lift
  // stays on the last card somebody pressed until they press another. Most
  // visitors to these sites are on a phone.
  assert.match(cssFor("hover"), /@media \(hover: hover\)/);
});

test("hover picks its selector from what the block DOES", () => {
  // The rule already in the source, generalised: a block that MOVES something
  // goes on buttons and cards only, because a raised input box reads as a fault
  // and a badge is a label rather than something you press.
  const moves = T.themeCss({ ...theme, hover: { css: "transform: translateY(-4px);" } });
  const tints = T.themeCss({ ...theme, hover: { css: "background-color: oklch(0.9 0.05 60);" } });
  const line = (css) => css.split("\n").find((l) => l.includes(":hover {")) || "";
  assert.doesNotMatch(line(moves), /input/, "a transform reached the input boxes");
  assert.match(line(tints), /input/, "a tint did NOT reach the input boxes");
});

test("focus stays on :focus-visible, never :focus", () => {
  // A mouse click on a plain `:focus` leaves a ring behind and the site reads as
  // broken to somebody who never used the keyboard.
  const css = cssFor("focus");
  assert.match(css, /:focus-visible/);
  assert.doesNotMatch(css.split("\n").filter((l) => l.includes("outline-width: 4px")).join("\n"),
    /[^-]:focus\s*[,{]/, "a bare :focus rule was emitted");
});

test("reveal cannot trap content invisible", () => {
  // The opacity-0 START exists ONLY inside both guards. No support or less
  // motion means not one rule is emitted and the section is simply visible —
  // the state it was in before the axis existed.
  const css = cssFor("reveal");
  assert.match(css, /@supports \(animation-timeline: view\(\)\)/);
  assert.match(css, /prefers-reduced-motion: no-preference/);
  const at = css.indexOf("opacity: 0");
  assert.ok(at > css.indexOf("@supports (animation-timeline"), "the from-state is outside the support guard");
});

test("the page transition SUPPRESSES under reduced motion rather than omitting", () => {
  // Dropping our rules there leaves the browser's OWN cross-fade standing, so a
  // visitor who asked for less motion gets MORE than one who did not.
  const css = cssFor("transition");
  assert.match(css, /prefers-reduced-motion: reduce/);
  assert.match(css, /animation: none/);
  // And both halves of the axis agree it is on — `pageCss` writes the animation
  // and `writeSiteBrand` writes the router flag, and a flag with no CSS gives
  // the browser's cross-fade on a site that asked for something else.
  assert.equal(T.transitionOn({ css: "opacity: 0;" }), true,
    "an authored transition would have had CSS and no router flag");
});

test("the ambient layer keeps pointer-events: none", () => {
  // Without it the fixed full-viewport layer swallows every click on the site —
  // which compiles, publishes, and looks like the whole page being dead.
  const css = cssFor("ambient");
  assert.match(css, /body::after \{[^}]*pointer-events: none/);
  assert.match(css, /body::after \{[^}]*position: fixed/);
  assert.match(css, /body::after \{[^}]*z-index: -1/);
});

test("the display colour still cannot land inside a filled primary panel", () => {
  // The one place this axis can make text unreadable: a heading INSIDE a filled
  // panel already has a foreground picked to be legible against it.
  assert.match(cssFor("display"), /:not\(:where\(\.bg-primary \*\)\)/);
});

test("a corner override still writes every element, and a token still comes first", () => {
  // The kit derives seven radius sizes from `--radius` with calc(), so a rule
  // reaching only cards leaves every chip and panel on the old shape — a page
  // rounded in some places and not others.
  const css = T.themeCss({ ...applied("corner"), radius: "1.1rem" });
  assert.match(css, /body, body \* \{[^}]*border-radius: 14px/);
  assert.ok(css.indexOf("--radius: 1.1rem") < css.indexOf("border-radius: 14px"),
    "the authored block must sit AFTER the token, or the token wins");
});

// ─────────────────────────────────────────────────────────────────────────────

test("the emitters read the SERIALISED block, never a raw field", () => {
  // The security property one module over: the pairs came out of a parser that
  // refused every character an escape would need, and the text reaching a
  // customer's stylesheet was assembled by us. An emitter reading a raw field
  // would put the model's own bytes back in the file.
  assert.equal(T.themeCss({ ...theme, hover: { value: "transform: translateY(-4px)" } }), BARE,
    "an emitter read something other than `.css`");
  assert.equal(T.themeCss({ ...theme, hover: { css: 42 } }), BARE, "a non-string css was emitted");
  assert.equal(T.themeCss({ ...theme, hover: { css: "" } }), BARE, "an empty block emitted a rule");
});

test("a ramp reaches its emitter in the shape the option table holds", () => {
  // What keeps an authored ramp and a named one indistinguishable downstream,
  // so no emitter has to learn a second shape.
  assert.match(cssFor("icon"), /stroke-width: 2\.75/);
  assert.match(cssFor("border"), /3px/);
  assert.match(cssFor("density"), /--spacing: 0\.37rem/);
  assert.match(cssFor("motion"), /--site-duration: 333ms/);
  assert.match(cssFor("motion"), /--site-ease: ease-in-out/);
});

test("every decls axis in the table is one an emitter really reads", () => {
  // Derived, so a fifteenth declaration axis added to the validator and read by
  // nothing fails HERE rather than on a customer's site.
  for (const axis of Object.keys(AXIS_DECLS)) {
    assert.notEqual(cssFor(axis), BARE, axis + " is in AXIS_DECLS and no emitter reads it");
  }
  for (const axis of Object.keys(AXIS_RAMPS)) {
    assert.notEqual(cssFor(axis), BARE, axis + " is in AXIS_RAMPS and no emitter reads it");
  }
});

test("nothing throws on a malformed authored value", () => {
  // `themeCss` runs in the container on the build path. A throw here is a failed
  // build wearing a container-died message.
  for (const axis of Object.keys(AXES)) {
    for (const junk of [{}, { css: null }, { layers: null }, [], 0, true, { steps: null }, { ratio: "x" }]) {
      assert.doesNotThrow(() => T.themeCss({ ...theme, [axis]: junk }),
        axis + " threw on " + JSON.stringify(junk));
    }
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// PARSESTYLE — the door every look goes through, widened from 2 axes to 23.

import { parseStyle, applyStyle, mergeStyle, MAX_STYLE_BUILD, AUTHORED_AXES } from "../builder/site-style.mjs";

test("every axis is authorable through parseStyle, derived at both ends", () => {
  assert.deepEqual([...AUTHORED_AXES].sort(), Object.keys(AXES).sort(),
    "an axis the engine has that parseStyle will not take authored is the enum by the side door");
});

test("A STORED NAME STILL PARSES — every site already published depends on it", () => {
  // Their `site_style` holds names and is re-parsed on EVERY publish. Reading a
  // bare string as CSS would refuse all of them, so each axis would fall back to
  // the default on the customer's next unrelated edit: a whole platform
  // re-styled by a typo fix, reported as a success.
  for (const [axis, spec] of Object.entries(AXES)) {
    for (const name of Object.keys(spec.options)) {
      const r = parseStyle({ [axis]: name }, { max: MAX_STYLE_BUILD });
      assert.equal(r.style[axis], name, axis + ": " + name + " stopped being read as a name");
      assert.deepEqual(r.dropped, [], axis + ": " + name + " was dropped");
    }
  }
});

test("a declaration block on the same axis is read as authored", () => {
  const r = parseStyle({ hover: "transform: translateY(-6px)" }, { max: MAX_STYLE_BUILD });
  assert.deepEqual(Object.keys(r.authored || {}), ["hover"]);
  assert.equal(r.style.hover, undefined, "an authored value must NOT land in the enum map");
  assert.deepEqual(r.dropped, []);
});

test("the `<axis>Css` field still works, so nothing already sending it breaks", () => {
  const r = parseStyle({ hoverCss: "opacity: 0.85" }, { max: MAX_STYLE_BUILD });
  assert.deepEqual(Object.keys(r.authored || {}), ["hover"],
    "the fold at the door stopped happening");
});

test("an authored axis costs one slot, exactly like a chosen one", () => {
  // Or the cap counts a look that moved eight axes as having moved two.
  const r = parseStyle({ hover: "opacity: 0.9", icon: { width: 2 }, corner: "border-radius: 4px" }, { max: 2 });
  assert.equal(Object.keys(r.authored || {}).length, 2, "the cap did not count authored axes");
  assert.equal(r.dropped.length, 1);
});

test("a refused block is reported to the CUSTOMER with its reason", () => {
  const r = parseStyle({ hover: "display: none" }, { max: MAX_STYLE_BUILD });
  assert.ok((r.refused || []).some((x) => x.axis === "hover"), "the refusal was silent");
  assert.ok(r.dropped.includes("hover"), "a refusal must also drop, or styleNote says nothing");
});

test("a deferred value is stored so the CONTAINER can judge it", () => {
  // The Worker holds three hex seeds and none of the 31 derived tokens, so a
  // block naming `var(--primary)` is a thing it cannot judge rather than a thing
  // the model got wrong. Refusing it here tells a customer their look failed
  // while it is painting on their site.
  const r = parseStyle({ hover: "background-color: var(--primary)" }, { max: MAX_STYLE_BUILD });
  assert.ok(r.authored && r.authored.hover, "a deferred value was not carried");
  assert.equal((r.refused || []).length, 0, "a deferred value was reported as refused");
  assert.deepEqual(r.dropped, []);
});

test("mergeStyle round-trips an authored value as its RAW SPEC", () => {
  // What is stored in `_meta` and sent to the container, and it is exactly the
  // shape `parseStyle` takes as input — so the container re-reads it with a
  // palette in hand and gets the real verdict. `mergeStyle` returning only the
  // enum map is what made the whole authored path unreachable for a day.
  const merged = mergeStyle({ icon: "heavy" }, { hover: "opacity: 0.8", icon: { width: 3 } });
  assert.equal(merged.hover, "opacity: 0.8", "the block did not survive the merge");
  assert.deepEqual(merged.icon, { width: 3 }, "the ramp did not survive the merge");
  // And it re-reads.
  const again = parseStyle(merged, { max: MAX_STYLE_BUILD });
  assert.deepEqual(Object.keys(again.authored || {}).sort(), ["hover", "icon"]);
});

test("mergeStyle keeps an EARLIER authored axis when a later patch does not name it", () => {
  // Absent means unchanged, everywhere in this product. Losing it is the
  // first-instruction-forgotten failure the merge exists to prevent.
  const merged = mergeStyle({ hover: "opacity: 0.8" }, { icon: { width: 3 } });
  assert.equal(merged.hover, "opacity: 0.8");
});

test("applyStyle puts the authored value where the EMITTER looks", () => {
  // TWO CONSUMERS OF ONE DECISION: `worldCss` reads the `authored` bag,
  // every other emitter reads `theme.<axis>`. A value reaching only one of them
  // is the wiring failure this repo has recorded twelve times — the build
  // succeeds and the look is silently unapplied.
  const t = applyStyle(theme, { hover: "transform: translateY(-6px)", icon: { width: 2.9 } });
  assert.equal(t.hover.css, "transform: translateY(-6px);", "the emitter would never have seen it");
  // A STRING, because that is what `ICON_STROKES` itself holds (`{width: "1.25"}`)
  // and `stroke-width` is unitless. The shape has to match the option table
  // exactly, or the authored path and the named path are two shapes downstream.
  assert.deepEqual(t.icon, { width: "2.9" });
  const css = T.themeCss(t);
  assert.match(css, /translateY\(-6px\)/);
  assert.match(css, /stroke-width: 2\.9/);
});

test("a site that authors nothing gets a byte-identical stylesheet", () => {
  assert.equal(T.themeCss(applyStyle(theme, {})), BARE);
  assert.equal(T.themeCss(applyStyle(theme, null)), BARE);
});

test("the legibility gate still refuses a wash the quiet ink cannot survive", () => {
  // The last gate, and the only one that needs the THEME as well as the value.
  // Widening the authored path must not have routed around it.
  const bad = applyStyle(theme, {
    backdrop: { light: ["linear-gradient(#fff6,#0000)"], dark: ["linear-gradient(#0006,#0000)"] },
  });
  assert.equal(Object.keys(bad.authored || {}).length, 0, "an illegible wash reached the stylesheet");
});

/* ------------------------------------------------- pressed, and its one difference */

test("PRESSED CARRIES NO HOVER GUARD — that guard is why it exists", () => {
  // `hoverCss` wraps itself in `@media (hover: hover)` because on a touch screen
  // `:hover` STICKS after a tap. The consequence nobody had followed through: on
  // a phone the hover state is deliberately dead and there was NOTHING behind
  // it. Measured before this axis: `:active` in 0 of 2,112 kit components and 0
  // of 329 corpus pages, and `button.tsx` carrying hover/focus-visible/disabled
  // and no active at all.
  //
  // So repeating the guard here would switch off the only feedback a phone gets
  // — the exact bug being fixed, restored by copying its sibling too faithfully.
  // DRIVEN THROUGH THE REAL VALIDATOR, never a raw string on the theme. The
  // first draft of this test did exactly that and reported the whole axis dead:
  // `authored()` reads `{css}`, so a bare string falls through to the named
  // branch, misses `PRESSED`, and emits nothing. The test was wrong and the
  // code was right — the same shape as a fixture more capable than reality, in
  // the other direction.
  const press = (decls) => {
    const r = readAuthoredAxis("pressed", decls);
    assert.equal(r.ok, true, "the validator refused: " + r.why);
    return T.themeCss({ ...theme, pressed: { css: r.css } });
  };
  const css = press("transform: scale(0.97)");
  assert.match(css, /scale\(0?\.97\)/, "the authored press never reached the stylesheet");
  const at = css.indexOf("scale(0.97)");
  const before = css.slice(0, at);
  const guardsOpen = (before.match(/@media[^{]*\(hover:\s*hover\)\s*\{/g) || []).length;
  const closes = (before.match(/\}/g) || []).length;
  assert.ok(guardsOpen === 0 || closes >= guardsOpen,
    "the press rule is inside @media (hover: hover) — a phone would never see it");
  assert.match(css, /:active/, "the press does not use :active at all");
});

test("the press selector follows what the block DOES, like hover's", () => {
  // A block that MOVES something reaches buttons and cards only — a squeezing
  // input box reads as a fault and a badge is a label rather than something you
  // press. One that only RECOLOURS reaches everything reactive. Asking the model
  // to know that would be a rule it eventually forgets.
  const press = (decls) => {
    const r = readAuthoredAxis("pressed", decls);
    assert.equal(r.ok, true, "the validator refused: " + r.why);
    return T.themeCss({ ...theme, pressed: { css: r.css } });
  };
  const moves = press("transform: translateY(1px)");
  const tints = press("opacity: 0.85");
  const line = (css) => (css.split("\n").find((l) => l.includes(":active")) || "");
  assert.ok(!line(moves).includes('[data-slot="input"]'),
    "a press that MOVES reached the input boxes");
  assert.ok(line(tints).includes('[data-slot="input"]'),
    "a press that only recolours did NOT reach everything reactive");
  for (const css of [moves, tints]) {
    assert.ok(line(css).includes('[data-slot="button"]:active'), "the press never reached a button");
  }
});

test("a site that asks for nothing gets NO press rule, so no existing site moves", () => {
  // `applyStyle` runs on EVERY publish of EVERY site — a text fix, a colour
  // change, a swapped picture. A non-`none` default would change how every
  // existing customer's buttons behave on touch on their next unrelated edit,
  // which is the "platform re-styled by a typo fix" failure this repo records.
  assert.equal(T.themeCss({ ...theme, pressed: undefined }), BARE);
  assert.equal(T.themeCss({ ...theme, pressed: "none" }), BARE);
  // And a nonsense value degrades to the same nothing rather than to a broken
  // rule — the fallthrough every axis here shares.
  assert.equal(T.themeCss({ ...theme, pressed: "constructor" }), BARE);
});
