// The person who filled in the form, coming back.
//
// `collect` is write-only by design: anyone may submit, nobody may read, because
// the rows are other visitors' submissions and listing them would hand a
// stranger every booking the shop has taken. That refusal is right, and it is
// also why — measured across every site the builder has made — a customer who
// booked a haircut could never see the appointment again, move it, or cancel it.
// The only person who could was the shop owner, inside isibi.
//
// This is the narrow exception, and it is narrow in a specific way: a claim
// token names ONE row. Holding it proves you are the person who wrote that row,
// because it was handed back only in the response to that insert. It buys the
// right to read that row and to cancel it, and it buys nothing else — no list,
// no filter, no ordering, no neighbouring id. There is deliberately no way to
// widen it, which is what keeps `collect` write-only for everyone else.
//
// Decisions only. Every side effect is injected, so all of this is driven
// against fakes in test/site-claim.test.mjs — no database, no Worker, no clock.

import { verifyClaim } from "./site-auth.mjs";

const json = (body, status = 200) => ({ body, status });

/**
 * Which tables a claim applies to.
 *
 * `collect` only, and the exclusions are each for a different reason:
 *   - `display` rows are the owner's own content, not anybody's submission;
 *   - `user` / `feed` / `admin` rows already HAVE an owner, so their author
 *     signs in and the ordinary owner-scoping applies. Minting a second,
 *     weaker credential for a row that already has a real one would be a way
 *     around the account, not a way in.
 */
export function claimable(def) {
  return String((def && def.access) || "collect").toLowerCase() === "collect";
}

/**
 * What the holder is shown.
 *
 * Their own submission, minus the two columns that are ours rather than theirs:
 * `_fts` is a generated search vector (meaningless to a client and often bigger
 * than the text it was built from) and `owner_id` is an internal id that is
 * always null on a `collect` row anyway. Everything else declared on the table
 * is returned, including anything the owner has since changed — a `status` that
 * now reads "confirmed" is precisely what the person wants to see.
 */
export function claimView(row) {
  if (!row || typeof row !== "object") return null;
  const out = {};
  for (const k of Object.keys(row)) {
    if (k === "_fts" || k === "owner_id") continue;
    out[k] = row[k];
  }
  return out;
}

/**
 * deps:
 *   verify(token, table, id) → payload | null    the HMAC check, key already bound to the site
 *   selectRow(table, id)     → row | null
 *   cancelRow(table, id)     → { changes }       soft-delete if the table declares trash
 */
export async function handleClaim(deps, { def, id, token, method } = {}) {
  // Not a claimable table. 404 rather than 403: a claim on a table that never
  // mints them is indistinguishable from a claim on a table that does not
  // exist, and saying which is which describes the site's schema to a stranger.
  if (!claimable(def)) return json({ error: "no such row" }, 404);

  // A positive integer, because it reaches SQL and because the id column is
  // `INTEGER GENERATED BY DEFAULT AS IDENTITY`. Refused here rather than
  // surfacing as a Postgres type error dressed up as a 500.
  if (!/^\d+$/.test(String(id == null ? "" : id))) return json({ error: "no such row" }, 404);

  const ok = await deps.verify(token, def.name, id);
  // The same answer as a row that is not there. A distinct "bad token" would
  // confirm the row exists to anyone guessing ids, which is exactly the oracle
  // the 404-not-403 rule closes everywhere else in this codebase.
  if (!ok) return json({ error: "no such row" }, 404);

  if (method === "GET") {
    const row = await deps.selectRow(def.name, id);
    if (!row) return json({ error: "no such row" }, 404);
    return json({ row: claimView(row) });
  }

  if (method === "DELETE") {
    const r = await deps.cancelRow(def.name, id);
    // Idempotent, and answering `ok` even when nothing changed is the point. A
    // cancel link gets clicked twice, gets prefetched, gets opened again to
    // check it worked. The holder proved with a valid token that this row was
    // theirs, so "it is not booked any more" tells them nothing they did not
    // already know — and a 404 on the second click reads as a broken link.
    return json({ ok: true, cancelled: true, changed: !!(r && r.changes) });
  }

  // Amending is not here yet, and 405 says so honestly rather than pretending
  // the row is missing. It is a real follow-up: the writable-column filter and
  // the constraint-error mapping both already exist, but a changed booking has
  // to re-run the uniqueness and overlap checks and deserves its own tests.
  return json({ error: "method not allowed" }, 405);
}

/** The one place that knows the query-string name, so nothing spells it twice. */
export const CLAIM_PARAM = "claim";

/** Re-exported so a caller wires one import rather than reaching past this. */
export { verifyClaim };
