// Copied from Lovable's template, with the ignores and the one restricted import changed to match
// our stack. Theirs bans the Next.js `server-only` package because TanStack Start has its own
// convention; we do not run Start, so that rule would never fire. What DOES go wrong here is a model
// reaching for the router it has seen most often, or importing the generated route tree by hand —
// both compile far enough to look fine and then behave wrongly, so they are errors.
import js from "@eslint/js";
import eslintPluginPrettier from "eslint-plugin-prettier/recommended";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  { ignores: ["dist", "src/routeTree.gen.ts"] },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "react-router-dom",
              message:
                "This app routes with @tanstack/react-router. Use <Link to=\"/…\"> and createFileRoute from '@tanstack/react-router'.",
            },
            {
              name: "./routeTree.gen",
              message:
                "src/routeTree.gen.ts is generated by `tsr generate`. Add a file under src/routes/ instead of importing the tree.",
            },
          ],
        },
      ],
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      // Theirs, kept: a generated page routinely destructures more than it uses, and failing a lint
      // run over that would cost a repair pass to fix nothing.
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  {
    // The router entry is the ONE file that legitimately imports the generated tree — that is how
    // the tree reaches the app at all. Restricting it everywhere else is the useful half of the rule.
    files: ["src/main.tsx"],
    rules: { "no-restricted-imports": "off" },
  },
  eslintPluginPrettier,
);
