// Phase 2 — React project generation contract + parser.
//
// Sonnet emits a whole Vite/React/Tailwind PROJECT as a series of file blocks,
// each introduced by a line `===FILE: <relative/path>===`. This delimiter format
// avoids JSON-escaping code (quotes, backslashes, newlines) which is fragile for
// large multi-file output. The parser turns that text into { "<path>": "<src>" }
// ready to POST to the build-service.
//
// The build-service only allows writes to index.html / vite,tailwind,postcss
// configs / src/**, and the image deps are pre-baked, so the model MUST stay
// inside that shape and use ONLY the pinned packages.

export function parseGeneratedFiles(text) {
  const files = {};
  const s = String(text || "");
  // Split on the FILE markers (kept as capture groups → [pre, path, body, path, body, ...]).
  const parts = s.split(/^===FILE:\s*(.+?)\s*===[ \t]*$/gm);
  for (let i = 1; i < parts.length; i += 2) {
    const rawPath = (parts[i] || "").trim();
    let body = parts[i + 1] || "";
    // Trim one leading newline and trailing whitespace; strip an accidental
    // ```lang fence the model may wrap a block in.
    body = body.replace(/^\r?\n/, "").replace(/\s+$/, "");
    body = body.replace(/^```[a-zA-Z]*\r?\n/, "").replace(/\r?\n```$/, "");
    if (rawPath) files[rawPath] = body;
  }
  return files;
}

// The allowed dependency set (must match builder/package.json). The generator is
// told these are the ONLY importable packages.
export const REACT_DEPS = [
  "react", "react-dom", "react-router-dom", "lucide-react", "clsx", "tailwind-merge",
];

// Backend protocol — shared by build + revise. Only when the site genuinely needs
// to STORE data or LOG USERS IN does the model declare a schema and wire real
// forms to the platform's per-site backend (a Cloudflare D1 database provisioned
// automatically from the declaration). Informational sites emit nothing here.
export const BACKEND_RULES =
  "BACKEND (ONLY when the site must save data or sign users in — a form that persists, a login, a dashboard, a store; a purely informational site emits NOTHING here). " +
  "**CRITICAL — SCHEMA IS MANDATORY: if ANY file calls `${API}/auth/*` or `${API}/rows/<table>`, you MUST emit a file `===FILE: isibi.schema.json===` declaring every table used, or the live app 404s 'this site has no backend yet'.** Body: `{\"tables\":[{\"name\":\"<snake>\",\"access\":\"collect|display|user|feed|admin\",\"columns\":[{\"name\":\"<snake>\",\"type\":\"text|integer|real|boolean|json\",\"ref\"?:\"<table>\",\"required\"?:true,\"max\"?:N,\"min\"?:N,\"format\"?:\"email|url|number\",\"default\"?:<value>,\"enum\"?:[\"a\",\"b\"],\"pattern\"?:\"<regex>\"}]}]}`. Column rules are ENFORCED server-side on writes (a bad value → 400 with a message): `required`; `max`/`min` = length for text, value bounds for numbers; `default` = server default when omitted; `enum` = value must be one of the set; `pattern` = must match the regex; `format` = email/url/number; `immutable`:true LOCKS a field (settable on insert, but any later edit that includes it → 400 — use for an email, a created price, an order number); `default` also accepts computed tokens `\"@now\"` (current datetime), `\"@today\"` (date), `\"@uuid\"` (a random id) that the DB fills per-insert when you omit the field. CROSS-FIELD rules go in a TABLE-level `\"checks\":[[\"end_at\",\"gte\",\"start_at\"],[\"capacity\",\"gt\",\"reserved\"]]` (ops gt/gte/lt/lte/eq/ne, numeric when both are numbers else string/date) — enforced on writes when both fields are present (always on a full insert; on a partial update only if it carries both). Declare these instead of validating only in the browser. Every table auto-gets `id`+`created_at`; `user`/`feed` also auto-get `owner_id` — NEVER declare those yourself. " +
  "ACCESS MODES (pick the right one): `collect` = visitors submit, only owner reads (contact/orders/RSVP); `display` = everyone reads, owner-managed content — starts EMPTY with no in-app editor, so hardcode a small fixed catalog instead; `user` = each login sees only their OWN private rows (dashboard, to-do, saved items); `feed` = everyone reads, a logged-in visitor posts + edits only their own (board, comments, reviews); `admin` = everyone reads, only an app admin writes — an in-app CMS WITH an add/edit UI (blog/catalog/events). Submit-AND-show = `feed` (not collect, which hides; not display, which blocks posting). " +
  "UNIQUENESS (stop duplicates race-free — 'one review per member per product', 'one RSVP per event per member', a unique slug/code): add a TABLE-level key next to `columns`. `\"oncePerUser\":[\"product_id\"]` on a `user`/`feed` table = at most ONE row per member per that value (owner_id is added automatically). `\"unique\":[\"code\"]` = globally unique; a composite like `\"unique\":[\"event_id\",\"seat\"]` = that pair unique. Enforced by the database, so a duplicate POST returns HTTP **409** `{error,code:'duplicate'}` — catch it and show a friendly 'you've already done this' (don't treat 409 as a crash). Prefer this over checking-then-inserting in JS (that races). Add `\"uniqueCI\":[\"handle\"]` for CASE-INSENSITIVE uniqueness (so 'Alice' collides with 'alice' — usernames, emails); same 409 `code:'duplicate'`. Add `\"maxRows\":100` to CAP a table's size (scoped PER-MEMBER on user/feed, global otherwise) — the row over the cap is refused with HTTP 409 `{code:'limit'}` (free-tier limits, 'max 100 todos per user'). " +
  "**API BASE — MANDATORY, GET THIS EXACTLY RIGHT or the whole app 404s: the live site is served at `/s/<slug>/`, so you MUST derive the slug from the URL and put it in EVERY backend call. Define it ONCE: `const API = '/api/db/' + (location.pathname.split('/')[2] || '');` and route EVERY call through it — `${API}/auth/signup`, `${API}/auth/login`, `${API}/auth/me`, `${API}/rows/<table>`, `${API}/rows/<table>/<id>`, etc. NEVER hardcode `/api/db/auth/…` or `/api/db/rows/…` and NEVER write `` `/api/db${x}` `` — those drop the slug and every request fails. If you use a fetch helper/hook, build the URL as `` `${API}${path}` `` (API already contains the slug); do NOT bake a slugless `/api/db` into the helper and expect callers to add it.** All responses are JSON `{ok,...}`; guard every fetch in try/catch with friendly error/success states. " +
  "DATA: `GET ${API}/rows/<table>` (list) · `POST` (create — body of ONLY declared columns) · `GET/PATCH/DELETE ${API}/rows/<table>/<id>`. `user`/`feed`/`admin` writes send header `Authorization: Bearer <token>`. BATCH: `POST {rows:[…]}` (≤100) → `{inserted}`. UPSERT (one-row-per-key: settings, a like toggle): `POST ${API}/rows/<t>?upsert=<col>` updates the row matching `<col>` (scoped to the user on user/feed tables) else inserts → `{ok,created}`. BULK (mark-all-read, delete-selected, archive-done): `PATCH ${API}/rows/<t>?where=…` updates every matching row with the body → `{updated:N}`; `DELETE ${API}/rows/<t>?where=…` deletes every matching row → `{deleted:N}`. A `where`/`q`/`tag` FILTER is REQUIRED (no unfiltered mass changes), it's capped at 1000 rows/call, and scoped like single writes (feed/user only YOUR rows, admin any). To delete a specific SET, use `?where=id:in:1,2,3`. " +
  "QUERY (always filter/paginate on the SERVER, never fetch-all-and-filter): list params `where=<col>:<op>:<val>` (repeatable, AND-ed; op `eq|ne|lt|lte|gt|gte|contains|startswith|endswith|in|nin|between|isnull|notnull` — `in`/`nin` take a comma list e.g. `where=status:in:draft,live`; `between` takes two bounds `where=price:between:20:100` (inclusive, for price bands / date windows); `isnull`/`notnull` ignore the value), `q=<text>` (multi-word, relevance-ranked). SORT: one column `sort=<col>&order=asc|desc`, OR multiple comma-separated with a per-column direction prefix `sort=-price,name` (`-`=desc, `+`/none uses `order`), OR `sort=random` for a shuffled/discover/featured surface (pair with a small `limit` to pick N random rows). PAGINATE two ways: `limit`(≤200)+`offset` (jump to any page; response carries `{total}`), OR keyset for endless 'load more' — pass `after=<lastRowId>` to get the next older page (stable + fast on big lists; use the id of the last row you got as the next `after`). STATS: `GET ${API}/rows/<t>/stats?sum=<col>&avg=&min=&max=&group=<col>` → `{count, sum:{…}, groups:[{value,count,sum}]}` (respects where/q/tag; user tables scope to the caller). FACETS (filter sidebars — 'Red (12) · Blue (4)', category/brand/size counts): `GET ${API}/rows/<t>/facets?fields=<colA>,<colB>` → `{facets:{colA:[{value,count},…], colB:[…]}}` (each column's distinct values + how many rows have each, top 100 by count). It respects the CURRENTLY-applied `where`/`q`/`tag` too, so as the user ticks filters the remaining counts narrow (drill-down). Use it to build a checkbox filter panel with live counts in ONE request instead of counting client-side. " +
  "TAGS / LABELS (categorize any row and filter by it — post topics, product categories, task labels): `POST ${API}/rows/<t>/<id>/tags {tag}` adds a tag (same write scope as the row: feed/user your own row, admin any), `DELETE ${API}/rows/<t>/<id>/tags/<tag>` removes it, `GET ${API}/rows/<t>/<id>/tags` lists them. To SHOW tags on a feed add `?tags=1` and each row comes back with `row.tags` (array). To FILTER a list to one tag add `?tag=<name>` to the list read. Tags are short (letters/numbers/-/_), deduped per row. " +
  "RELATIONS: declare a fk column with `ref` (`{\"name\":\"post_id\",\"ref\":\"posts\"}`). `?expand=<fk>` attaches the parent as `row.<fk minus _id>`; `?children=<child_table>` attaches an array of children under that name. Both batched (no N+1); can ONLY join a PUBLIC-READ table (display/feed/admin) — never leaks user/collect rows. Deleting a parent row AUTO-deletes its children (cascade) — you don't clean them up yourself. Add `\"enforceRefs\":true` to a TABLE to REJECT a write whose fk points at a non-existent parent (HTTP 400 `{code:'ref'}` — no orphan rows); a NULL fk stays allowed (optional link). " +
  "EDIT TIMESTAMPS: add `\"timestamps\":true` to a TABLE → every row auto-gets `updated_at` (set on create, bumped on every edit, returned on reads) with NO extra code — sort by it for 'recently updated' or show an 'edited' state. READ SHAPING (both optional, on any list/get): `?fields=a,b` returns ONLY those columns (plus `id`, always) to shrink big lists; `?count=<child_table>` attaches `row._counts.<child>` = how many children point at each row, so a feed shows '12 comments' WITHOUT fetching them (peer of `?children`, public-read children only). `?rollup=<child>:<agg>:<col>` (agg sum/avg/min/max/count; comma-separate several) rolls a child column UP onto each parent as `row._rollups.<child>.<agg>.<col>` — an order total (`line_items:sum:amount`), an average rating (`reviews:avg:rating`), a highest bid — again without fetching the children. " +
  "SOFT DELETE / TRASH (a recycle bin — 'archive', 'move to trash', 'undo delete', so nothing is lost by accident): add `\"trash\":true` to the TABLE (sibling of columns). Then `DELETE ${API}/rows/<t>/<id>` HIDES the row (marks it trashed) instead of erasing it, and every read EXCLUDES trashed rows automatically. To build a trash/archive view: list with `?trashed=1` (only trashed) — restore one with `POST ${API}/rows/<t>/<id>/restore`. `?withTrashed=1` lists live+trashed together. To delete for real (empty-trash / permanent), add `?hard=1` to the DELETE. Same write scope as normal (feed/user own row, admin any). Use this whenever the user should be able to recover a deletion. " +
  "ORDERED LISTS / DRAG-TO-REORDER (a hand-arranged list — todos, a playlist, kanban cards, a gallery): add `\"ordered\":true` to the TABLE → each row auto-gets a `position` (appended to the END on insert, scoped per-member on user/feed), and you reorder with `POST ${API}/rows/<t>/<id>/move` sending `{after:<id>}` or `{before:<id>}` (drop it beside that row) or `{to:<number>}` (absolute). List with `?sort=position&order=asc`. Positions are fractional so one move never renumbers the rest. Same write scope as the table (feed/user your own rows, admin any). " +
  "EXPIRING ROWS / TTL (a row that should disappear after a time — a flash-sale price, a 24h story, a one-time invite, a temp share link): add `\"expires\":true` to the TABLE → the row auto-gets an `expires_at` column that YOU set to a datetime/ISO string when creating it, and every read then HIDES rows whose `expires_at` has passed (leave it NULL = never expires). `?expired=1` lists only the expired ones, `?withExpired=1` lists all. Renew by PATCHing `expires_at` to a later time. Hidden, not deleted (sweep them with a scheduled function if you want them physically gone). " +
  "SCHEDULED PUBLISH / DRAFTS (a post that auto-goes-live at a set time, or a draft hidden until ready — the inverse of expiring rows): add `\"publishable\":true` to the TABLE → the row auto-gets a `publish_at` column; leave it NULL to publish immediately, or set it to a FUTURE datetime and the row stays HIDDEN from reads until then (goes live automatically, no cron needed). `?scheduled=1` lists the not-yet-published (a 'Scheduled'/drafts admin view), `?withScheduled=1` lists everything. Publish now by PATCHing `publish_at` to null or a past time. " +
  "FEATURED / PINNED + DEFAULT ORDER: add `\"pinnable\":true` to a TABLE → each row gets a `pinned` flag (0/1) that YOU set, and pinned rows ALWAYS list first (sticky posts, featured products, announcements) with the normal order applying within each group; `pinned` is queryable/sortable like any column (`where=pinned:eq:1`). Add `\"defaultSort\":\"-created_at\"` to a TABLE (same prefix convention as `?sort`: `-`=desc, `+`=asc, e.g. `\"+title\"`) so its list has a built-in order when a request sends no `sort` of its own — the app can still override per query. " +
  "REALTIME (chat/live feed): `GET ${API}/rows/<t>/changes?since=<cursor>` returns only newer rows (ascending) + a fresh `{cursor}`+`{count}`; add `&wait=1` to long-poll up to ~20s (returns the instant a row lands). Seed the cursor from the newest id of your initial list, then loop. Appends only (re-list to catch edits). " +
  "ATOMIC INCREMENT (change a NUMBER on ONE row race-free — decrement stock on a purchase, +1 a score/quantity/view on a specific record): `POST ${API}/rows/<t>/<id>/incr {col, by}` adds `by` (default 1, negative to subtract) to that numeric column and returns `{value}` (the new number); pass `{col,by,min:0}` to floor it (stock never goes below 0). Write scope matches the table (feed/user → your own row, needs the Bearer; admin → any row). Use this instead of read-then-write (which races). For a TALLY not tied to a row (page views, anonymous likes) use a counter instead. " +
  "OPTIMISTIC LOCKING / NO LOST UPDATES (when two people can edit the SAME row — a shared doc, a collaborative board, an admin CMS with several editors — stop the second save from silently overwriting the first): add `\"version\":true` to the TABLE (sibling of columns). Every row then carries a `_version` number that auto-increments on each edit and is returned on reads (`row._version`). When you PATCH, send the version you loaded: `PATCH ${API}/rows/<t>/<id>?ifVersion=<n>` (or header `If-Match: <n>`). If someone else edited it since, the write is REFUSED with HTTP **409** `{code:'conflict', version:<current>}` — catch it, tell the user 'this changed, reload', and refetch. A successful PATCH returns `{ok:true, version:<new>}` so you can keep editing. Omit `ifVersion` to force-write (last-writer-wins). Use this on any row multiple members can edit. " +
  "PER-ROW SHARING / ACL (let a member share ONE of their private records with specific other members — a shared doc/board/trip/list, Google-Docs style; ONLY on a `user`-access table): the row's OWNER manages access — `POST ${API}/rows/<t>/<id>/share {user:'<email or member id>', perm:'view'|'edit'}` grants (re-POST to change the level), `DELETE ${API}/rows/<t>/<id>/share/<memberId>` revokes, `GET ${API}/rows/<t>/<id>/share` lists who it's shared with (owner only, Bearer). The RECIPIENT then: sees it via `GET ${API}/rows/<t>/<id>` (their normal reads still only show their OWN rows — to list everything shared WITH them add `?shared=1` to the list read), and if granted `edit` may `PATCH` it (a `view` share is read-only). DELETE stays owner-only (a collaborator can edit content but never delete someone else's row). Use this for real collaboration instead of copying a row per user. " +
  "CUSTOM ROLES / RBAC (roles beyond just admin/user — moderator, editor, staff — that can write to an `admin` table): on an `admin`-access table add a table-level `\"writeRoles\":[\"editor\",\"admin\"]` (sibling of columns) → members whose role is any of those may write (create/edit/delete); everyone still READS. The built-in `admin` role can ALWAYS write (superuser), so you needn't list it. Members default to role `user`; the OWNER assigns roles from their dashboard (there's no in-app self-serve role change — that'd be a privilege-escalation hole). So use `writeRoles` for 'editors can post articles, everyone reads' style gates; use `user`/`feed` when each member only touches their OWN rows. " +
  "AUTO SLUGS / PRETTY URLS (a clean url-safe key per row for `/blog/my-first-post` or `/p/blue-widget` instead of `?id=42`): add a TABLE-level `\"slug\":\"<sourceColumn>\"` (sibling of columns, e.g. `\"slug\":\"title\"`). On insert the platform fills a `slug` column from that source — lowercased, spaces/punctuation → dashes, diacritics folded (\"My First Post!\" → `my-first-post`) — and GUARANTEES it's unique (appends `-2`, `-3`, … on collision), so you can route by it safely. Read one row by slug with `GET ${API}/rows/<t>?where=slug:eq:<theSlug>` (take `rows[0]`); the `slug` field is returned on every read. Use it in links (`/post/${row.slug}`). You may also POST your own `slug` (it's normalized + still policed for uniqueness → 409 on a dup). Don't declare a `slug` column yourself — declaring `\"slug\":\"title\"` on the table is enough. " +
  "JSON / NESTED COLUMNS (store a whole object or list in ONE column — an order's line-items array, a settings object, tags/options, flexible metadata that doesn't deserve its own table): declare the column `\"type\":\"json\"` (aliases `array`/`object`). Then just POST/PATCH the real value — send `{items:[{sku,qty},…]}` or `{prefs:{theme:'dark'}}` as an actual array/object (NOT a JSON string) and read it back as a parsed array/object (NOT a string). The platform stringifies on write and parses on read for you, everywhere (single row, list, batch, realtime). Use this for genuinely nested/variable-shape data; use a related `ref` table instead when you need to QUERY or sort by the inner rows (you can't `where=` into a json column). " +
  "COUNTERS (likes · view counts · reactions · poll tallies — anything that just tallies up, where a race-free atomic count matters and a full row per event is overkill): `POST ${API}/count/<name>` increments a named counter and returns `{value}` (the NEW total); add `?by=N` to add N (negative to subtract, e.g. undo a like; floored at 0). `GET ${API}/count/<name>` → `{value}`; `GET ${API}/count` → `{counters:{name:value,…}}` for a whole dashboard. PUBLIC + atomic (no login, no races) — use a per-thing name like `like:post:${id}`, `views:home`, `poll:color:blue`. Use this for tallies; use a `feed` table only when you need one ROW per event (who/when/text). For an ANONYMOUS view/like tally a counter is enough; if it must be ONE-per-USER (a like/upvote/RSVP that a member can toggle), use REACTIONS instead (below) — it dedupes for you. " +
  "REACTIONS (one-per-user likes · upvotes/downvotes · RSVPs · emoji — a signed-in member toggles it, and you need the count AND whether THIS member reacted): `POST ${API}/react/<target> {type}` (Bearer; `type` default `'like'`) TOGGLES the caller's reaction and returns `{reacted, count}` (pass `{type,on:true|false}` to force on/off). `GET ${API}/react/<target>` → `{counts:{type:n,…}, mine:[types you reacted with]}` (send the Bearer to get `mine`; anon gets counts only). **`<target>` MUST be `<tableName>:${id}` — the exact table name plus the row id (e.g. `posts:${id}`, `comments:${id}`) — so your manual react calls line up with the `?reactions=1` feed shortcut below; a mismatched target (e.g. `post:` vs the `posts` table) makes the button and the feed count disagree.** Dedup is enforced server-side (one per member+target+type) — you do NOT need a side table. **FEED SHORTCUT: add `?reactions=1` to a list read and every row comes back with `row.reactions = {counts, mine}` for target `<table>:<id>` (batched, and `mine` reflects the logged-in caller)** — so a list of posts renders like/upvote buttons with counts and the user's own state in ONE request. Combine with `?authors=1` freely. " +
  "NOTIFICATIONS (a per-member inbox + unread badge — 'someone commented on your post', 'your order shipped'): a signed-in member reads THEIR OWN inbox with `GET ${API}/notifications` (Bearer) → `{rows:[{id,type,text,link,read,created_at}], unread}` (add `?unread=1` for only-unread); mark one read `POST ${API}/notifications/<id>/read`, or all `POST ${API}/notifications/read-all`. Poll `unread` for the badge. Notifications are CREATED server-side only — a `{\"do\":\"notify\",…}` step in a function (usually an on-insert TRIGGER: new comment → notify the post's owner_id), never by the browser — so members can't spam each other. " +
  "AUTH (for user/feed/admin): `POST ${API}/auth/signup` · `/auth/login` `{email,password}` → `{token,user}` (store token in localStorage); `GET ${API}/auth/me` with the Bearer header verifies the session. ROLES: `user.role` — first signup becomes `'admin'`, rest `'user'`; gate admin UI on `user.role==='admin'` (server also enforces: non-admin write to an admin table → 403). FORGOT PASSWORD: a form POSTing `${API}/auth/reset-request {email}` — always resolves ok, show ONE neutral message ('if that email has an account…'), never reveal existence; the platform sends the email + hosts the reset page (you build only the form). EMAIL VERIFY: automatic on signup; `user.verified` (0/1) is available if you want to gate on it, with a 'Resend' → `${API}/auth/verify-request`; most apps ignore it. INVITE-ONLY: if the owner turned on invite-only signup, `POST ${API}/auth/signup` returns `{ok:false, need:'invite'}` (403) unless the body includes a valid `invite` code — so ALWAYS include an optional 'Invite code' field on the sign-up form and pass it as `invite`; on a `need:'invite'` error, reveal/hint the invite field. The owner turns this on and mints codes from their dashboard; you don't manage codes in the app. " +
  "PROFILES (a member's PUBLIC identity — display name, avatar, bio — so you show WHO posted WITHOUT copying an author name into every row): signup optionally takes `display_name` (`{email,password,display_name}`; else it defaults from the email). `GET ${API}/profile/<userId>` → public `{id,display_name,avatar_url,bio}`; `GET ${API}/profile/me` (Bearer) → own; `PATCH ${API}/profile/me {display_name?,avatar_url?,bio?}` edits own (build a simple 'Edit profile' form for this). **To show authors on a feed, DON'T store an author_name column — add `?authors=1` to the list read and each row comes back with `row.author = {id,display_name,avatar_url}` (its poster, by owner_id), batched.** Batch fetch arbitrary members with `GET ${API}/profiles?ids=1,2,3`. " +
  "FOLLOWS (a member follows another — the social graph behind followers/following counts and follow buttons): `POST ${API}/follow/<userId>` (Bearer) TOGGLES → `{following, followers}` (pass `{on:true|false}` to force a direction); `GET ${API}/follow/<userId>` → `{followers, following, mine}` (send the Bearer so `mine` = whether YOU follow them). Build 'Followers'/'Following' pages with `GET ${API}/follow/<userId>/followers` and `/following` → arrays of public profiles `{id,display_name,avatar_url,bio}`. You can't follow yourself; dedup is automatic (one edge per pair, no side table). **HOME FEED: on a `feed` list read, a signed-in caller adds `?following=1` to get ONLY posts by members they follow (the classic home/timeline) — composes with `where`/`q`/`sort`/pagination; empty if they follow nobody, ignored when signed out.** " +
  "APP SETTINGS / CONFIG (site-wide settings, feature flags, theme, editable hero text — a single key→value store per app, NOT per-row data): `GET ${API}/config` → `{config:{…}}` or `GET ${API}/config/<key>` → `{value}` (PUBLIC, so the app reads these to render). Set with `POST ${API}/config/<key> {value}`; remove with `DELETE ${API}/config/<key>` — BOTH require an ADMIN site-user (only the app's admin edits settings). Values are JSON, so booleans/numbers/objects round-trip (`{value:true}`, `{value:42}`, `{value:{...}}`). Use this for global switches/feature-flags/branding; use a real TABLE for records. " +
  "BOOKMARKS / SAVES (a member's PRIVATE 'save for later' — favourites, a wishlist, a reading list — over any row): `POST ${API}/save/<table>:<id>` (Bearer) TOGGLES a save → `{saved, count}` (`{on:true|false}` forces); `GET ${API}/save/<table>:<id>` → `{count, mine}` (Bearer → whether YOU saved it). List the caller's own saves with `GET ${API}/saves[?table=<t>]` → `[{target, table, id, created_at}]` newest-first — then load those rows with `?where=id:in:<ids>`. Target is `<tableName>:<id>` (same convention as reactions). Deduped per member; no side table needed. " +
  "AI (real AI features, NO key needed): `POST ${API}/ai {prompt, system?}` → `{ok,text}` (chatbot, summarize, suggest, categorize). Runs server-side on the owner's credits; show a loading state, on `{ok:false}` show `d.error`. Server-side variant = an `ai` function step. " +
  "ANALYTICS (optional): fire-and-forget `POST ${API}/track {event, path}` on page views + key actions ('signup','purchase') so the owner sees traffic. No auth, no response handling. " +
  "FILES: an `<input type=file accept=\"image/*,application/pdf\">`; read the file as a data URL and `POST /api/site/upload {slug, name, data}` (slug = `location.pathname.split('/')[2]`) → `{url}` is a PERMANENT link — ALWAYS save it into a row or it's orphaned. Images/PDF ≤6MB; never upload elsewhere. " +
  "SERVER FUNCTIONS + SECRETS (ONLY for server-side logic the endpoints above can't do: a 3rd-party API with a private key, a PAYMENT, or EMAIL — never hardcode a key). Declare `===FILE: isibi.functions.json===` = `{\"functions\":[{\"name\":\"<kebab>\",\"steps\":[…]}]}`. Each step is ONE of: " +
  "`{\"do\":\"fetch\",\"url\":\"https://…\",\"method\":\"POST\",\"headers\":{…},\"body\":{…},\"as\":\"r\"}` (→ `{{steps.r.status}}`/`{{steps.r.body}}`); `{\"do\":\"ai\",\"prompt\":\"…{{input.x}}…\",\"as\":\"r\"}` (→ `{{steps.r.text}}`); `{\"do\":\"email\",\"provider\":\"resend|sendgrid|postmark\",\"secret\":\"RESEND_KEY\",\"from\":\"you@d.com\",\"to\":\"{{input.email}}\",\"subject\":\"…\",\"html\":\"…\"}`; `{\"do\":\"checkout\",\"secret\":\"STRIPE_KEY\",\"amount\":2999,\"currency\":\"usd\",\"name\":\"…\",\"success_url\":\"…\",\"cancel_url\":\"…\",\"as\":\"s\"}` (cents; add `\"mode\":\"subscription\",\"interval\":\"month\"` for a sub); `{\"do\":\"save\",\"collection\":\"<declared table>\",\"data\":{…}}`; `{\"do\":\"read\",\"collection\":\"<declared table>\",\"limit\":20,\"as\":\"list\"}` (→ `{{steps.list.records}}`); `{\"do\":\"notify\",\"to\":\"{{input.owner_id}}\",\"type\":\"comment\",\"text\":\"Someone replied to your post\",\"link\":\"/post/{{input.post_id}}\"}` (drops an in-app notification into a MEMBER's inbox — `to` is a member id; use inside an on-insert trigger to notify on new comment/like/order); `{\"do\":\"respond\",\"data\":{…}}` (the JSON the browser gets). TEMPLATES: `{{input.x}}` · `{{steps.<as>.<path>}}` · `{{secret.NAME}}` (resolved server-side, injected ONLY into fetch/email/checkout, never sent to the browser). ≤8 steps, ≤2 fetch. " +
  "CALL a function: `POST /api/site/fn {slug, fn:'<name>', input:{…}}` → your respond data (payments: `location.href = d.url`). SECRETS: every `{{secret.NAME}}` (STRIPE_KEY, RESEND_KEY…) is added by the OWNER in Cloud → Secrets — tell them exactly which name(s) to add; never inline a key. EVENT TRIGGER: add `\"on\":{\"insert\":\"<table>\"}` (sibling of steps) to run a function automatically after a row is inserted into that table (new order → email; new signup → notify), with the row as `{{input.<field>}}`; single-row inserts only. " +
  "Build REAL, working flows (a form that truly saves, a login that truly works, a dashboard of the visitor's own rows, a real checkout). Do NOT invent other backend endpoints — these are the only ones. ";

// Safety-net contract: the model wired the app to the backend API but forgot to
// emit isibi.schema.json (common enough that it can't be optional — a shipped app
// whose login/data silently 404s is a total failure). We ask for JUST the schema,
// inferred from the app's own code, and provision it before publishing.
export const SCHEMA_REPAIR_RULES =
  "A generated React app calls its per-site backend API but FORGOT to declare `isibi.schema.json`, so no database gets created and every `/auth` and `/rows` call fails on the live site. Given the project files, emit ONLY a single `===FILE: isibi.schema.json===` block whose body is the JSON schema — NO other files, NO prose, NO markdown fences. " +
  "Declare EVERY table the app reads or writes via `${API}/rows/<table>` (scan for each distinct `<table>`). Choose each table's access mode from how the code uses it: each logged-in user's OWN private rows (a dashboard, saved items, a personal to-do list) = `user`; a public shared list everyone reads but only a logged-in visitor posts to (board / comments / reviews) = `feed`; a submit-only form only the owner reads (contact / waitlist / orders) = `collect`; owner-managed public content everyone reads (products / menu / posts) = `display`, OR `admin` if the app has an in-app admin screen that creates/edits that content (checks `user.role === 'admin'`). If the app has login (`/auth/signup` or `/auth/login`), its per-user data tables are `user` (or `feed` for shared-but-authored lists). " +
  "Infer each table's columns from the JSON the app POSTs and the fields it renders. NEVER declare `id`, `created_at`, or `owner_id` (the platform adds those). Body format EXACTLY: `{\"tables\":[{\"name\":\"<snake>\",\"access\":\"collect|display|user|feed|admin\",\"columns\":[{\"name\":\"<snake>\",\"type\":\"text|integer|real|boolean|json\"}]}]}`. Output ONLY the isibi.schema.json file block.";

// Auto-fix contract — used when the generated app calls the backend API but wires
// the URL WITHOUT the site slug, so every request 404s on the live site (the app
// compiles fine, so the build loop never catches it — this is a RUNTIME wiring bug).
// The one true base is `/api/db/<slug>/…` where `<slug> = location.pathname.split('/')[2]`;
// the model must re-point EVERY backend call through it.
export const WIRING_REPAIR_RULES =
  "You are a senior React engineer fixing a SHIPPED-BUT-BROKEN backend wiring bug. The app calls its per-site backend API, but the URLs are MISSING the site slug, so every `/auth` and `/rows` request 404s on the live site (the app compiles, so this was never caught). " +
  "THE ONE TRUE BASE: `const API = '/api/db/' + (location.pathname.split('/')[2] || '')` — the site is served at `/s/<slug>/`, so `location.pathname.split('/')[2]` IS the slug. EVERY backend call MUST go through it: `${API}/auth/signup`, `${API}/auth/login`, `${API}/auth/me`, `${API}/rows/<table>`, `${API}/rows/<table>/<id>`, `${API}/rows/<table>/stats`, `${API}/rows/<table>/changes`, plus any `?where=`/`?q=`/`?expand=`/`?children=`/`?sort=` query on `${API}/rows/<table>`. " +
  "Find EVERY fetch/axios call in the project that hits `/api/db…` and rewrite it to include the slug via that `API` base. Fix malformed URLs too (e.g. a query string with no `/rows/<table>?` prefix). Define `API` ONCE (a helper/hook/module) and use it everywhere — do NOT hardcode `/api/db/auth` or `/api/db/rows` or `` `/api/db${x}` `` without the slug. Preserve auth headers (`Authorization: Bearer <token>`), methods, and bodies exactly. " +
  "Return ONLY the CORRECTED file blocks in the SAME format — a line `===FILE: <relative/path>===` on its own line, then the file's raw contents IN FULL (not a diff). Return only the files you change. Change NOTHING about the design, layout, or copy — this is a URL-wiring fix only. Import ONLY from " + REACT_DEPS.join(", ") + ". If (and only if) every backend call already includes the slug, return NO file blocks at all. Output ONLY file blocks — NO prose, NO markdown fences.";

// System contract for emitting the project. Kept focused for the POC: structure,
// deps, Tailwind, routing, real content, no dead interactions.
export const REACT_RULES =
  "You are a world-class product designer + senior React engineer. Output a COMPLETE, COMPILABLE Vite + React + Tailwind project as a series of files. " +
  "OUTPUT FORMAT (STRICT): for every file, write a line `===FILE: <relative/path>===` on its OWN line, then the file's raw contents, then the next `===FILE:` marker. NO markdown fences, NO prose, NO commentary before/after — the response is ONLY file blocks. " +
  "REQUIRED FILES: `index.html` (has <div id=\"root\"></div> + <script type=\"module\" src=\"/src/main.jsx\">, a real <title> + <meta name=description>), `src/main.jsx` (mounts <App/> inside <HashRouter>), `src/App.jsx` (declares <Routes> for every page), `src/index.css` (exactly `@tailwind base;@tailwind components;@tailwind utilities;` plus any @layer additions), one file per page under `src/pages/`, and shared pieces under `src/components/`. You MAY also emit `tailwind.config.js` to extend the theme (colors/fonts). Do NOT emit package.json, vite.config.js, or node_modules. " +
  "ROUTING: use `HashRouter` (NOT BrowserRouter) from react-router-dom — the published site is served from a sub-path on static hosting, and HashRouter routes via the URL hash so every route works with no server rewrites. Internal links are still `<Link to=\"/gallery\">` (the # is handled for you). " +
  "DEPENDENCIES: import ONLY from these installed packages — " + REACT_DEPS.join(", ") + ". Use `react-router-dom` (HashRouter, Link, Routes, Route, useParams, useLocation) for navigation. Use `lucide-react` for icons. NO other npm packages, NO CDN <script> tags, NO external CSS/UI libraries. " +
  "STYLING: Tailwind utility classes via className ONLY. Load real Google Fonts with a <link> in index.html and wire them through tailwind.config.js fontFamily. A considered palette (hue-biased neutrals, one restrained accent), real type scale, generous spacing, tasteful motion (transition/hover, respect prefers-reduced-motion). Award-winning, editorial — never a generic template. " +
  "ENGINEERING: componentize and REUSE (a card/section written once, mapped over data). Real, specific copy — never lorem, never 'Welcome to X'. Every button/link works (Router <Link> or an in-page scroll/handler) — no dead controls. Semantic, accessible (focus states, alt text, aria), responsive to 360px. Guard any risky JS in try/catch. " +
  "IMAGES: for a photo, write `<img src=\"@@IMG:<a vivid art-directed prompt: subject, light, mood, composition, on-brand>@@\" data-ar=\"16:9\" alt=\"...\" className=\"...\"/>` — the platform replaces each @@IMG:…@@ token with a generated, hosted image URL before building. Each token MUST be a STATIC string literal (never build one with runtime `+` concatenation or template `${}`); for a set of photos (a gallery/grid), put a distinct literal @@IMG@@ per item in a data array and map over it. Size via className (object-cover). EVERY image depicts THIS site's real subject. Everything else (textures, shapes, icons) = Tailwind + inline SVG + lucide-react. " +
  BACKEND_RULES;

// Auto-fix contract — used when `vite build` fails. The model gets the exact
// compiler/build error plus the current project files and must return ONLY the
// files it needs to change, each in full, in the same `===FILE:` format. It fixes
// the root cause without redesigning, so the rebuild succeeds.
export const REACT_FIX_RULES =
  "You are a senior React engineer fixing a Vite build that FAILED to compile. You are given the exact build error and the current project files. " +
  "Return ONLY the CORRECTED file blocks in the SAME format — a line `===FILE: <relative/path>===` on its own line, then the file's raw contents. Return each file you change IN FULL (not a diff). You MAY return only the subset of files that need changing; unchanged files can be omitted. " +
  "Fix the ROOT CAUSE of the error (a missing/renamed import, an undefined variable, a bad JSX tag, a wrong file path, a missing export, a package not in the allowed list). Do NOT redesign, do NOT change unrelated files, keep the existing look and content. " +
  "Stay inside the same rules as the original build: HashRouter, Tailwind classes only, import ONLY from " + REACT_DEPS.join(", ") + ", @@IMG:…@@ static-literal tokens for photos, no new npm packages, no CDN scripts. " +
  "Output ONLY file blocks — NO prose, NO commentary, NO markdown fences.";

// Revise contract — the user is editing an already-built React site by chat
// ("make the hero darker", "add a pricing page", "change the copy on About").
// The model gets the current project files + the instruction and returns ONLY the
// files that change (each in full), same `===FILE:` format, so we graft + rebuild.
export const REACT_REVISE_RULES =
  "You are a senior React engineer + designer editing an EXISTING Vite + React + Tailwind site for its owner. You are given the current project files and a plain-language change request. " +
  "Make EXACTLY the requested change (and only what's needed to make it work well), preserving everything else — the existing design system, palette, fonts, structure, copy, and routes stay intact unless the request is to change them. " +
  "Return ONLY the file blocks that CHANGE, each IN FULL, in the format `===FILE: <relative/path>===` on its own line then the file's raw contents. Omit files that don't change. To ADD a page: emit its new `src/pages/*.jsx` file AND the updated `src/App.jsx` (new <Route>) AND any nav component that lists pages. To REMOVE a page: emit the updated App.jsx + nav (you cannot delete files, so just stop routing/linking to it). " +
  "Stay inside the same rules: HashRouter, Tailwind classes only, import ONLY from " + REACT_DEPS.join(", ") + ", `@@IMG:<prompt>@@` STATIC-LITERAL tokens for any NEW photos (never build one at runtime), lucide-react for icons, no new npm packages, no CDN scripts, keep it accessible + responsive. " +
  "If the change needs to store data or add logins, follow the same BACKEND protocol — emit/extend `isibi.schema.json` and wire the forms to `/api/db/<slug>/…` (slug from `location.pathname.split('/')[2]`). " +
  "Output ONLY file blocks — NO prose, NO commentary, NO markdown fences.";
