// scaffold.mjs — the $0 half of a build. Everything here is produced by CODE, not by a model, so it costs no
// output tokens and can never truncate:
//
//   src/routes.js  — the page manifest (path + label per page), derived from the page files that exist
//   src/App.jsx    — the <Routes> table, derived from the same manifest
//
// This replaces the model-written router that truncated mid-<Routes> and killed a whole 60k build: a for-loop
// cannot run out of budget. It also means adding a page automatically wires its route AND its nav link (the
// templated Nav imports navLinks from routes.js), so a page-generation step only has to emit its own page file.
//
// Pure + dependency-free so it is trivially unit-testable.

// Page name → URL path. Home is "/", SignIn is "/signin", everything else is kebab-cased.
export function routeForPage(name) {
  if (name === "Home") return "/";
  if (name === "SignIn") return "/signin";
  return "/" + String(name).replace(/([a-z0-9])([A-Z])/g, "$1-$2").replace(/_/g, "-").toLowerCase();
}

// Page name → human label for the nav ("SalesQuota" → "Sales Quota", "TrackEmail" → "Track Email").
export function labelForPage(name) {
  return String(name).replace(/([a-z0-9])([A-Z])/g, "$1 $2").replace(/[-_]/g, " ").trim();
}

// pageNamesFrom(files) — the page components present, in a stable order: Home first, SignIn second, then the
// feature pages alphabetically, with Admin last (it belongs at the end of a nav).
export function pageNamesFrom(files) {
  const names = Object.keys(files || {})
    .map((p) => (p.match(/^src\/pages\/([A-Za-z0-9_]+)\.jsx$/) || [])[1])
    .filter(Boolean);
  const rank = (n) => (n === "Home" ? 0 : n === "SignIn" ? 1 : n === "Admin" ? 3 : 2);
  return [...new Set(names)].sort((a, b) => rank(a) - rank(b) || a.localeCompare(b));
}

// routesModule(pages) — src/routes.js: the manifest the templated Nav reads. SignIn is excluded from navLinks
// (it lives in the nav's sign-in button, not the link row).
export function routesModule(pages) {
  const rows = pages.map((n) => `  { name: '${n}', to: '${routeForPage(n)}', label: '${labelForPage(n)}' },`).join("\n");
  return "// GENERATED by the scaffold from the pages that exist — do not edit by hand.\n" +
    "export const routes = [\n" + rows + "\n];\n\n" +
    "// Links shown in the top nav (sign-in is handled by the nav's own button).\n" +
    "export const navLinks = routes.filter((r) => r.name !== 'SignIn');\n";
}

// appModule(pages) — src/App.jsx: imports every page and declares its <Route>, wrapped in the shared Nav.
export function appModule(pages) {
  const imports = pages.map((n) => `import ${n} from './pages/${n}.jsx';`).join("\n");
  const routes = pages.map((n) => `        <Route path="${routeForPage(n)}" element={<${n} />} />`).join("\n");
  return "// GENERATED by the scaffold from the pages that exist — do not edit by hand.\n" +
    "import { Routes, Route } from 'react-router-dom';\n" +
    "import Nav from './components/Nav.jsx';\n" +
    imports + "\n\n" +
    "export default function App() {\n" +
    "  return (\n" +
    "    <div className=\"min-h-screen flex flex-col\">\n" +
    "      <Nav />\n" +
    "      <main className=\"flex-1\">\n" +
    "        <Routes>\n" +
    routes + "\n" +
    "        </Routes>\n" +
    "      </main>\n" +
    "    </div>\n" +
    "  );\n}\n";
}

// scaffoldRouting(files) → the same files plus generated src/routes.js and src/App.jsx. Any model-emitted App.jsx
// is REPLACED: routing is owned by code. Returns { files, pages } so callers can log what got wired.
export function scaffoldRouting(files) {
  const out = { ...(files || {}) };
  const pages = pageNamesFrom(out);
  if (!pages.length) return { files: out, pages };
  out["src/routes.js"] = routesModule(pages);
  out["src/App.jsx"] = appModule(pages);
  return { files: out, pages };
}
