// scaffold.mjs — the $0 half of a build. Everything here is produced by CODE, not by a model, so it costs no
// output tokens and can never truncate:
//
//   src/routes.ts  — the page manifest (path + label per page), derived from the page files that exist
//   src/App.tsx    — the <Routes> table, derived from the same manifest
//
// This replaces the model-written router that truncated mid-<Routes> and killed a whole 60k build: a for-loop
// cannot run out of budget. It also means adding a page automatically wires its route AND its nav link (the
// templated Nav imports navLinks from routes.js), so a page-generation step only has to emit its own page file.
//
// Pure + dependency-free so it is trivially unit-testable.

// Page name → URL path. Home is "/", SignIn is "/signin", everything else is kebab-cased.
export function routeForPage(name) {
  if (name === "Home") return "/";
  if (name === "SignIn") return "/signin";
  return "/" + String(name).replace(/([a-z0-9])([A-Z])/g, "$1-$2").replace(/_/g, "-").toLowerCase();
}

// Page name → human label for the nav ("SalesQuota" → "Sales Quota", "TrackEmail" → "Track Email").
export function labelForPage(name) {
  return String(name).replace(/([a-z0-9])([A-Z])/g, "$1 $2").replace(/[-_]/g, " ").trim();
}

// pageNamesFrom(files, order) — the page components present, in a stable order: Home first, SignIn second, then
// the feature pages, with Admin last (it belongs at the end of a nav).
//
// `order` is an optional preferred sequence for the middle group. Alphabetical is a fine default for pages we
// know nothing about, but it is wrong whenever the pages form a JOURNEY: a shop's nav read "Cart, Orders, Shop",
// which puts the checkout before the thing being bought. A starter knows its own journey and declares it; any
// page not named in `order` still appears, alphabetically, after the ones that are.
export function pageNamesFrom(files, order = []) {
  const names = Object.keys(files || {})
    // Accept BOTH extensions: the kit is .tsx, but a model may still emit .jsx and the page should route.
    .map((p) => (p.match(/^src\/pages\/([A-Za-z0-9_]+)\.[jt]sx$/) || [])[1])
    .filter(Boolean);
  const rank = (n) => (n === "Home" ? 0 : n === "SignIn" ? 1 : n === "Admin" ? 3 : 2);
  const pref = (n) => { const i = order.indexOf(n); return i === -1 ? order.length : i; };
  return [...new Set(names)].sort((a, b) => rank(a) - rank(b) || pref(a) - pref(b) || a.localeCompare(b));
}

// pageExtsFrom(files) — name → the extension the page ACTUALLY has. The router must import the real file: if a
// model emits Home.jsx and we generate `import Home from './pages/Home.tsx'`, the build fails on a missing
// module. Defaults to .tsx, which is what the kit and the rules ask for.
export function pageExtsFrom(files) {
  const exts = {};
  for (const p of Object.keys(files || {})) {
    const m = p.match(/^src\/pages\/([A-Za-z0-9_]+)\.([jt]sx)$/);
    if (m) exts[m[1]] = m[2];
  }
  return exts;
}

// routesModule(pages) — src/routes.ts: the manifest the templated Nav reads. SignIn is excluded from navLinks
// (it lives in the nav's sign-in button, not the link row).
export function routesModule(pages) {
  const rows = pages.map((n) => `  { name: '${n}', to: '${routeForPage(n)}', label: '${labelForPage(n)}' },`).join("\n");
  return "// GENERATED by the scaffold from the pages that exist — do not edit by hand.\n" +
    "export const routes = [\n" + rows + "\n];\n\n" +
    "// Links shown in the top nav (sign-in is handled by the nav's own button).\n" +
    "export const navLinks = routes.filter((r) => r.name !== 'SignIn');\n";
}

// appModule(pages) — src/App.tsx: imports every page and declares its <Route>, wrapped in the shared Nav.
export function appModule(pages, exts = {}) {
  const imports = pages.map((n) => `import ${n} from './pages/${n}.${exts[n] || 'tsx'}';`).join("\n");
  const routes = pages.map((n) => `        <Route path="${routeForPage(n)}" element={<${n} />} />`).join("\n");
  return "// GENERATED by the scaffold from the pages that exist — do not edit by hand.\n" +
    "import { Routes, Route } from 'react-router-dom';\n" +
    "import Nav from './components/Nav.tsx';\n" +
    imports + "\n\n" +
    "export default function App() {\n" +
    "  return (\n" +
    "    <div className=\"min-h-screen flex flex-col\">\n" +
    "      <Nav />\n" +
    "      <main className=\"flex-1\">\n" +
    "        <Routes>\n" +
    routes + "\n" +
    "        </Routes>\n" +
    "      </main>\n" +
    "    </div>\n" +
    "  );\n}\n";
}

// scaffoldRouting(files) → the same files plus generated src/routes.ts and src/App.tsx. Any model-emitted App
// is REPLACED: routing is owned by code. Returns { files, pages } so callers can log what got wired.
export function scaffoldRouting(files, opts = {}) {
  const out = { ...(files || {}) };
  const pages = pageNamesFrom(out, opts.navOrder || []);
  if (!pages.length) return { files: out, pages };
  out["src/routes.ts"] = routesModule(pages);
  out["src/App.tsx"] = appModule(pages, pageExtsFrom(out));
  return { files: out, pages };
}

// ─────────────────────────────────────────────────────────────────────────────
// THEMING — the 72 components are written against SEMANTIC tokens (ink-50..900,
// brand-50..900, accent-*, canvas, surface, brandfg, font-display/sans, shadow-soft,
// rounded-xl2). The token NAMES never change; only their VALUES do. So we can give
// every app its own palette without touching a single component — generated in code,
// $0, from the style family the planner already picks.
//
// The ink ramp is SEMANTIC, not literal: ink-50 is always "faintest fill" and ink-900
// is always "strongest text". On a dark family the ramp inverts, so `text-ink-900`
// stays readable and `bg-ink-100` stays a subtle fill — with no component changes.

const hex2rgb = (h) => {
  const s = String(h).replace('#', '');
  const n = s.length === 3 ? s.split('').map((c) => c + c).join('') : s;
  return [parseInt(n.slice(0, 2), 16), parseInt(n.slice(2, 4), 16), parseInt(n.slice(4, 6), 16)];
};
const rgb2hex = (r, g, b) => '#' + [r, g, b].map((v) => Math.max(0, Math.min(255, Math.round(v))).toString(16).padStart(2, '0')).join('');

function rgb2hsl(r, g, b) {
  r /= 255; g /= 255; b /= 255;
  const max = Math.max(r, g, b), min = Math.min(r, g, b);
  const l = (max + min) / 2;
  if (max === min) return [0, 0, l];
  const d = max - min;
  const s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
  let h;
  if (max === r) h = ((g - b) / d + (g < b ? 6 : 0));
  else if (max === g) h = (b - r) / d + 2;
  else h = (r - g) / d + 4;
  return [h / 6, s, l];
}
function hsl2rgb(h, s, l) {
  if (s === 0) { const v = l * 255; return [v, v, v]; }
  const q = l < 0.5 ? l * (1 + s) : l + s - l * s;
  const p = 2 * l - q;
  const f = (t) => {
    if (t < 0) t += 1; if (t > 1) t -= 1;
    if (t < 1 / 6) return p + (q - p) * 6 * t;
    if (t < 1 / 2) return q;
    if (t < 2 / 3) return p + (q - p) * (2 / 3 - t) * 6;
    return p;
  };
  return [f(h + 1 / 3) * 255, f(h) * 255, f(h - 1 / 3) * 255];
}

// ramp(baseHex, lightnesses, satScale) → a 50..900 scale that keeps the base hue.
function ramp(baseHex, stops, satAdjust = []) {
  const [h, s] = rgb2hsl(...hex2rgb(baseHex));
  const keys = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900];
  const out = {};
  keys.forEach((k, i) => {
    const sat = Math.max(0, Math.min(1, s * (satAdjust[i] ?? 1)));
    out[k] = rgb2hex(...hsl2rgb(h, sat, stops[i]));
  });
  return out;
}

// isDark(hex) — relative luminance test, used to decide whether the ink ramp inverts.
export function isDark(hex) {
  const [r, g, b] = hex2rgb(hex).map((v) => { const c = v / 255; return c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4); });
  return 0.2126 * r + 0.7152 * g + 0.0722 * b < 0.4;
}

// themeFor(family) → the token values for one style family (tokens from design-system.mjs).
export function themeFor(tokens) {
  const t = tokens || {};
  const dark = isDark(t.bg || '#ffffff');
  // Light theme: ink goes light→dark. Dark theme: the same ramp INVERTED, so ink-900
  // is still "strongest text" (now near-white) and ink-100 is still a subtle fill.
  const neutralStops = dark
    ? [0.14, 0.18, 0.24, 0.34, 0.46, 0.58, 0.68, 0.78, 0.87, 0.95]
    : [0.975, 0.945, 0.88, 0.76, 0.60, 0.46, 0.36, 0.27, 0.18, 0.10];
  // Neutrals carry a whisper of the accent hue so they read as chosen, not default grey.
  const ink = ramp(t.muted || t.text || '#71717a', neutralStops, [0.35, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.8]);
  const brand = ramp(t.accent || '#4a6df5', dark
    ? [0.20, 0.26, 0.34, 0.44, 0.54, 0.62, 0.70, 0.78, 0.85, 0.91]
    : [0.965, 0.925, 0.855, 0.755, 0.66, 0.58, 0.48, 0.39, 0.31, 0.24]);
  const accent = ramp(t.accent2 || '#f97a17', dark
    ? [0.22, 0.28, 0.36, 0.46, 0.56, 0.64, 0.72, 0.80, 0.86, 0.92]
    : [0.965, 0.925, 0.86, 0.76, 0.67, 0.59, 0.50, 0.41, 0.33, 0.26]);
  return {
    canvas: t.bg || '#ffffff',
    surface: t.surface || (dark ? '#16141c' : '#ffffff'),
    brandfg: t.accentFg || '#ffffff',
    ink, brand, accent,
    radius: t.radius || '0.75rem',
    shadow: t.shadow || '0 1px 2px rgba(0,0,0,.04), 0 8px 24px -12px rgba(0,0,0,.12)',
    fontDisplay: t.fontDisplay || "system-ui, sans-serif",
    fontBody: t.fontBody || "system-ui, -apple-system, sans-serif",
    dark,
  };
}

// tailwindConfig(theme) → the generated tailwind.config.js for an app.
export function tailwindConfig(theme) {
  const scale = (o) => '{ ' + Object.entries(o).map(([k, v]) => `${k}: '${v}'`).join(', ') + ' }';
  return `// GENERATED per app — the component library reads these token NAMES; only the values change.
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        display: [${JSON.stringify(theme.fontDisplay).slice(1, -1).split(', ').map((f) => `'${f.replace(/'/g, '')}'`).join(', ')}],
        sans: [${JSON.stringify(theme.fontBody).slice(1, -1).split(', ').map((f) => `'${f.replace(/'/g, '')}'`).join(', ')}],
      },
      colors: {
        canvas: '${theme.canvas}',
        surface: '${theme.surface}',
        brandfg: '${theme.brandfg}',
        ink: ${scale(theme.ink)},
        brand: ${scale(theme.brand)},
        accent: ${scale(theme.accent)},
      },
      boxShadow: { soft: '${theme.shadow}' },
      borderRadius: { xl2: '${theme.radius}' },
    },
  },
  plugins: [],
}
`;
}

// scaffoldTheme(files, tokens) — write the per-app tailwind.config.js into the file set.
export function scaffoldTheme(files, tokens) {
  const out = { ...(files || {}) };
  out['tailwind.config.js'] = tailwindConfig(themeFor(tokens));
  return out;
}

// ─────────────────────────────────────────────────────────────────────────────
// SCHEMA → TYPESCRIPT. The app declares its tables in isibi.schema.json; this turns that declaration into real
// types, in code, for $0. It is the same trick Lovable gets by generating types from its SQL migrations, and the
// reason to copy it is that a hand-kept type and a real schema drift the first time anyone adds a column.
//
// What it buys, concretely: `useResource('bookings')` now returns `Booking[]` with no annotation at the call
// site, a column typo is a compile error instead of `undefined` on screen, and an enum column becomes a literal
// union — so `status: 'confirmd'` fails to build rather than being silently rejected by the server at runtime.
//
// Unknown table names still resolve to `any` rather than erroring, because a brief can name a table before the
// schema catches up and a build must never die over that.

const SQL_TO_TS = { text: 'string', integer: 'number', real: 'number', number: 'number', boolean: 'boolean', json: 'any' };

// Table name → the interface name used in the generated file ("booking_notes" → "BookingNote").
export function typeNameFor(table) {
  const pascal = String(table).replace(/(^|[_-])([a-z0-9])/g, (_, __, c) => c.toUpperCase()).replace(/[_-]/g, '');
  return pascal.replace(/ies$/, 'y').replace(/([^s])s$/, '$1'); // crude singular: Bookings → Booking, Categories → Category
}

function columnType(col) {
  // An enum column is the highest-value case: the server rejects anything outside the set with a 400, so the
  // union turns a runtime rejection into a compile error.
  if (Array.isArray(col.enum) && col.enum.length) return col.enum.map((v) => `'${String(v).replace(/'/g, "\\'")}'`).join(' | ');
  return SQL_TO_TS[String(col.type || 'text').toLowerCase()] || 'any';
}

// The columns the PLATFORM adds — they are never declared in the schema but every row comes back with them.
function platformColumns(t) {
  const cols = [['id', 'number'], ['created_at', 'string']];
  if (t.access === 'user' || t.access === 'feed') cols.push(['owner_id', 'number']);
  if (t.timestamps) cols.push(['updated_at', 'string']);
  if (t.trash) cols.push(['deleted_at', 'string | null']);
  if (t.teamScope && t.access === 'user') cols.push(['team_id', 'number | null']);
  return cols;
}

// dbTypesModule(spec) → the source of src/lib/db-types.ts for one app's schema.
export function dbTypesModule(spec) {
  const tables = (spec && Array.isArray(spec.tables) ? spec.tables : []).filter((t) => t && t.name);
  const head = '// GENERATED from isibi.schema.json — do not edit by hand. Change the schema and this follows.\n';
  if (!tables.length) {
    return head + '\n// This app declares no tables, so every useResource row stays `any`.\nexport interface Tables {}\n';
  }
  const blocks = tables.map((t) => {
    const rows = [
      ...platformColumns(t).map(([n, ty]) => `  ${n}: ${ty}`),
      ...(Array.isArray(t.columns) ? t.columns : []).filter((c) => c && c.name).map((c) => {
        // `required` mirrors the server's own validation: a required column is always present on a row that
        // came back, everything else may be null.
        const opt = c.required ? '' : '?';
        const ty = columnType(c);
        return `  ${c.name}${opt}: ${ty}${c.required ? '' : ' | null'}`;
      }),
    ];
    return `/** \`${t.name}\` (access: ${t.access || 'user'}) */\nexport interface ${typeNameFor(t.name)} {\n${rows.join('\n')}\n}`;
  });
  const map = tables.map((t) => `  ${t.name}: ${typeNameFor(t.name)}`).join('\n');
  return head + '\n' + blocks.join('\n\n') +
    '\n\n/** Table name → row type. `useResource` reads this, so a known table needs no annotation. */\n' +
    `export interface Tables {\n${map}\n}\n\nexport type TableName = keyof Tables\n`;
}

// scaffoldDbTypes(files) — write src/lib/db-types.ts from whatever isibi.schema.json the app ended up with.
// Always emits a file, even with no schema, so `useResource` can import it unconditionally.
export function scaffoldDbTypes(files) {
  const out = { ...(files || {}) };
  let spec = null;
  try { spec = JSON.parse(out['isibi.schema.json'] || '{}'); } catch { spec = null; }
  out['src/lib/db-types.ts'] = dbTypesModule(spec);
  return out;
}

// ─────────────────────────────────────────────────────────────────────────────
// AGENTS.md — the instructions that ship INSIDE the generated project.
//
// Everything the generator knows about how to work on an isibi app currently lives in our pipeline, which means
// it evaporates the moment the code leaves us: a customer who downloads the repo and opens it in Cursor or
// Claude Code hands their agent 258 unfamiliar components and no rules, and it starts hand-rolling fetch calls
// and rewriting the router. This file is the rules travelling WITH the code.
//
// Generated, not written — so it is $0, and it can describe THIS app's real tables and pages rather than a
// generic template that would go stale on the first schema change.

const bullet = (s) => `- ${s}`;

export function agentsMd(files, meta = {}) {
  const spec = (() => { try { return JSON.parse(files['isibi.schema.json'] || '{}'); } catch { return {}; } })();
  const tables = Array.isArray(spec.tables) ? spec.tables : [];
  const pages = pageNamesFrom(files);
  const name = meta.name || 'This app';

  const ACCESS_NOTES = {
    admin: 'anyone can read; only an admin account can write',
    user: "each signed-in user sees only their OWN rows" ,
    feed: 'everyone reads; a signed-in user posts and edits their own',
    collect: 'write-only from the client — submissions cannot be read back',
    display: 'everyone reads; the owner maintains it',
  };

  const L = [];
  L.push(`# Working on ${name}`);
  L.push('');
  L.push('Generated by isibi. This file is for whatever coding agent opens this repo next — read it before');
  L.push('changing anything, because several files here are produced by a program and editing them by hand is');
  L.push('wasted work: the next build overwrites them.');
  L.push('');
  L.push('## Do not edit these — they are generated');
  L.push(bullet('`src/App.tsx` and `src/routes.ts` — the router and the nav, derived from whichever files exist in `src/pages/`. To add a page, add the file; the route and the nav link appear on their own.'));
  L.push(bullet('`tailwind.config.js` — the whole palette, computed from one base colour. Change the design tokens, never the hex values.'));
  L.push(bullet('`src/lib/db-types.ts` — the row types, derived from `isibi.schema.json`. Change the schema and these follow.'));
  L.push('');
  L.push('## How to talk to the database');
  L.push('```tsx');
  L.push("const { data, loading, error, saving, create, update, remove } = useResource('" + (tables[0] ? tables[0].name : 'table') + "')");
  L.push('```');
  L.push(bullet('`data` is always an array and is TYPED from the schema — no annotation needed.'));
  L.push(bullet('Writes refresh the list themselves. Never refetch by hand after a create or update.'));
  L.push(bullet('`useRecord(table, id)` is the single-row version for a detail view.'));
  L.push(bullet('Do NOT hand-roll `useState` + `useEffect` + `fetch` for table data — it loses the shared cache and the auto-refresh.'));
  L.push(bullet('`api.*` from `src/lib/api.js` is only for what `useResource` does not wrap: `/auth/*` and sub-actions like `/rows/<t>/<id>/restore`.'));
  L.push('');
  if (tables.length) {
    L.push('## This app\'s tables');
    L.push('');
    L.push('| table | access | means |');
    L.push('| --- | --- | --- |');
    for (const t of tables) L.push(`| \`${t.name}\` | ${t.access || 'user'} | ${ACCESS_NOTES[t.access] || 'see isibi.schema.json'} |`);
    L.push('');
    const gated = tables.filter((t) => t.transitions);
    if (gated.length) {
      L.push('Status changes are enforced SERVER-SIDE on ' + gated.map((t) => '`' + t.name + '`').join(', ') +
        ' (see `transitions` in the schema). Offering a move the server will reject just produces a 409 the user cannot act on — only offer the legal ones.');
      L.push('');
    }
  }
  L.push('## The component kit');
  L.push(bullet('`src/components/` holds the shared components. Import them; do not recreate a card, table, modal or empty state that already exists.'));
  L.push(bullet('`Modal`, `Dropdown`, `Popover`, `Tooltip` and `MultiSelect` are backed by Radix for focus trapping and keyboard navigation. Do not replace them with plain divs.'));
  L.push(bullet('Style with the semantic tokens (`ink-*`, `brand-*`, `accent-*`, `surface`, `canvas`) rather than literal colours, so the palette keeps working.'));
  L.push('');
  if (pages.length) { L.push('## Pages'); L.push(pages.map((p) => '`' + p + '`').join(' · ')); L.push(''); }
  L.push('## House rules');
  L.push(bullet('Every list needs a real empty state saying what will appear there — never a blank page.'));
  L.push(bullet('Every form disables its submit while saving and shows the server\'s own error message on failure.'));
  L.push(bullet('Confirm before anything destructive.'));
  return L.join('\n') + '\n';
}

// scaffoldAgentsMd(files, meta) — write AGENTS.md into the file set.
export function scaffoldAgentsMd(files, meta = {}) {
  const out = { ...(files || {}) };
  out['AGENTS.md'] = agentsMd(out, meta);
  return out;
}
