// scaffold.mjs — the $0 half of a build. Everything here is produced by CODE, not by a model, so it costs no
// output tokens and can never truncate:
//
//   src/routes.ts  — the page manifest (path + label per page), derived from the page files that exist
//   src/App.tsx    — the <Routes> table, derived from the same manifest
//
// This replaces the model-written router that truncated mid-<Routes> and killed a whole 60k build: a for-loop
// cannot run out of budget. It also means adding a page automatically wires its route AND its nav link (the
// templated Nav imports navLinks from routes.js), so a page-generation step only has to emit its own page file.
//
// Pure + dependency-free so it is trivially unit-testable.

// Page name → URL path. Home is "/", SignIn is "/signin", everything else is kebab-cased.
export function routeForPage(name) {
  if (name === "Home") return "/";
  if (name === "SignIn") return "/signin";
  return "/" + String(name).replace(/([a-z0-9])([A-Z])/g, "$1-$2").replace(/_/g, "-").toLowerCase();
}

// Page name → human label for the nav ("SalesQuota" → "Sales Quota", "TrackEmail" → "Track Email").
export function labelForPage(name) {
  return String(name).replace(/([a-z0-9])([A-Z])/g, "$1 $2").replace(/[-_]/g, " ").trim();
}

// pageNamesFrom(files) — the page components present, in a stable order: Home first, SignIn second, then the
// feature pages alphabetically, with Admin last (it belongs at the end of a nav).
export function pageNamesFrom(files) {
  const names = Object.keys(files || {})
    // Accept BOTH extensions: the kit is .tsx, but a model may still emit .jsx and the page should route.
    .map((p) => (p.match(/^src\/pages\/([A-Za-z0-9_]+)\.[jt]sx$/) || [])[1])
    .filter(Boolean);
  const rank = (n) => (n === "Home" ? 0 : n === "SignIn" ? 1 : n === "Admin" ? 3 : 2);
  return [...new Set(names)].sort((a, b) => rank(a) - rank(b) || a.localeCompare(b));
}

// pageExtsFrom(files) — name → the extension the page ACTUALLY has. The router must import the real file: if a
// model emits Home.jsx and we generate `import Home from './pages/Home.tsx'`, the build fails on a missing
// module. Defaults to .tsx, which is what the kit and the rules ask for.
export function pageExtsFrom(files) {
  const exts = {};
  for (const p of Object.keys(files || {})) {
    const m = p.match(/^src\/pages\/([A-Za-z0-9_]+)\.([jt]sx)$/);
    if (m) exts[m[1]] = m[2];
  }
  return exts;
}

// routesModule(pages) — src/routes.ts: the manifest the templated Nav reads. SignIn is excluded from navLinks
// (it lives in the nav's sign-in button, not the link row).
export function routesModule(pages) {
  const rows = pages.map((n) => `  { name: '${n}', to: '${routeForPage(n)}', label: '${labelForPage(n)}' },`).join("\n");
  return "// GENERATED by the scaffold from the pages that exist — do not edit by hand.\n" +
    "export const routes = [\n" + rows + "\n];\n\n" +
    "// Links shown in the top nav (sign-in is handled by the nav's own button).\n" +
    "export const navLinks = routes.filter((r) => r.name !== 'SignIn');\n";
}

// appModule(pages) — src/App.tsx: imports every page and declares its <Route>, wrapped in the shared Nav.
export function appModule(pages, exts = {}) {
  const imports = pages.map((n) => `import ${n} from './pages/${n}.${exts[n] || 'tsx'}';`).join("\n");
  const routes = pages.map((n) => `        <Route path="${routeForPage(n)}" element={<${n} />} />`).join("\n");
  return "// GENERATED by the scaffold from the pages that exist — do not edit by hand.\n" +
    "import { Routes, Route } from 'react-router-dom';\n" +
    "import Nav from './components/Nav.tsx';\n" +
    imports + "\n\n" +
    "export default function App() {\n" +
    "  return (\n" +
    "    <div className=\"min-h-screen flex flex-col\">\n" +
    "      <Nav />\n" +
    "      <main className=\"flex-1\">\n" +
    "        <Routes>\n" +
    routes + "\n" +
    "        </Routes>\n" +
    "      </main>\n" +
    "    </div>\n" +
    "  );\n}\n";
}

// scaffoldRouting(files) → the same files plus generated src/routes.ts and src/App.tsx. Any model-emitted App
// is REPLACED: routing is owned by code. Returns { files, pages } so callers can log what got wired.
export function scaffoldRouting(files) {
  const out = { ...(files || {}) };
  const pages = pageNamesFrom(out);
  if (!pages.length) return { files: out, pages };
  out["src/routes.ts"] = routesModule(pages);
  out["src/App.tsx"] = appModule(pages, pageExtsFrom(out));
  return { files: out, pages };
}

// ─────────────────────────────────────────────────────────────────────────────
// THEMING — the 72 components are written against SEMANTIC tokens (ink-50..900,
// brand-50..900, accent-*, canvas, surface, brandfg, font-display/sans, shadow-soft,
// rounded-xl2). The token NAMES never change; only their VALUES do. So we can give
// every app its own palette without touching a single component — generated in code,
// $0, from the style family the planner already picks.
//
// The ink ramp is SEMANTIC, not literal: ink-50 is always "faintest fill" and ink-900
// is always "strongest text". On a dark family the ramp inverts, so `text-ink-900`
// stays readable and `bg-ink-100` stays a subtle fill — with no component changes.

const hex2rgb = (h) => {
  const s = String(h).replace('#', '');
  const n = s.length === 3 ? s.split('').map((c) => c + c).join('') : s;
  return [parseInt(n.slice(0, 2), 16), parseInt(n.slice(2, 4), 16), parseInt(n.slice(4, 6), 16)];
};
const rgb2hex = (r, g, b) => '#' + [r, g, b].map((v) => Math.max(0, Math.min(255, Math.round(v))).toString(16).padStart(2, '0')).join('');

function rgb2hsl(r, g, b) {
  r /= 255; g /= 255; b /= 255;
  const max = Math.max(r, g, b), min = Math.min(r, g, b);
  const l = (max + min) / 2;
  if (max === min) return [0, 0, l];
  const d = max - min;
  const s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
  let h;
  if (max === r) h = ((g - b) / d + (g < b ? 6 : 0));
  else if (max === g) h = (b - r) / d + 2;
  else h = (r - g) / d + 4;
  return [h / 6, s, l];
}
function hsl2rgb(h, s, l) {
  if (s === 0) { const v = l * 255; return [v, v, v]; }
  const q = l < 0.5 ? l * (1 + s) : l + s - l * s;
  const p = 2 * l - q;
  const f = (t) => {
    if (t < 0) t += 1; if (t > 1) t -= 1;
    if (t < 1 / 6) return p + (q - p) * 6 * t;
    if (t < 1 / 2) return q;
    if (t < 2 / 3) return p + (q - p) * (2 / 3 - t) * 6;
    return p;
  };
  return [f(h + 1 / 3) * 255, f(h) * 255, f(h - 1 / 3) * 255];
}

// ramp(baseHex, lightnesses, satScale) → a 50..900 scale that keeps the base hue.
function ramp(baseHex, stops, satAdjust = []) {
  const [h, s] = rgb2hsl(...hex2rgb(baseHex));
  const keys = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900];
  const out = {};
  keys.forEach((k, i) => {
    const sat = Math.max(0, Math.min(1, s * (satAdjust[i] ?? 1)));
    out[k] = rgb2hex(...hsl2rgb(h, sat, stops[i]));
  });
  return out;
}

// isDark(hex) — relative luminance test, used to decide whether the ink ramp inverts.
export function isDark(hex) {
  const [r, g, b] = hex2rgb(hex).map((v) => { const c = v / 255; return c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4); });
  return 0.2126 * r + 0.7152 * g + 0.0722 * b < 0.4;
}

// themeFor(family) → the token values for one style family (tokens from design-system.mjs).
export function themeFor(tokens) {
  const t = tokens || {};
  const dark = isDark(t.bg || '#ffffff');
  // Light theme: ink goes light→dark. Dark theme: the same ramp INVERTED, so ink-900
  // is still "strongest text" (now near-white) and ink-100 is still a subtle fill.
  const neutralStops = dark
    ? [0.14, 0.18, 0.24, 0.34, 0.46, 0.58, 0.68, 0.78, 0.87, 0.95]
    : [0.975, 0.945, 0.88, 0.76, 0.60, 0.46, 0.36, 0.27, 0.18, 0.10];
  // Neutrals carry a whisper of the accent hue so they read as chosen, not default grey.
  const ink = ramp(t.muted || t.text || '#71717a', neutralStops, [0.35, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.8]);
  const brand = ramp(t.accent || '#4a6df5', dark
    ? [0.20, 0.26, 0.34, 0.44, 0.54, 0.62, 0.70, 0.78, 0.85, 0.91]
    : [0.965, 0.925, 0.855, 0.755, 0.66, 0.58, 0.48, 0.39, 0.31, 0.24]);
  const accent = ramp(t.accent2 || '#f97a17', dark
    ? [0.22, 0.28, 0.36, 0.46, 0.56, 0.64, 0.72, 0.80, 0.86, 0.92]
    : [0.965, 0.925, 0.86, 0.76, 0.67, 0.59, 0.50, 0.41, 0.33, 0.26]);
  return {
    canvas: t.bg || '#ffffff',
    surface: t.surface || (dark ? '#16141c' : '#ffffff'),
    brandfg: t.accentFg || '#ffffff',
    ink, brand, accent,
    radius: t.radius || '0.75rem',
    shadow: t.shadow || '0 1px 2px rgba(0,0,0,.04), 0 8px 24px -12px rgba(0,0,0,.12)',
    fontDisplay: t.fontDisplay || "system-ui, sans-serif",
    fontBody: t.fontBody || "system-ui, -apple-system, sans-serif",
    dark,
  };
}

// tailwindConfig(theme) → the generated tailwind.config.js for an app.
export function tailwindConfig(theme) {
  const scale = (o) => '{ ' + Object.entries(o).map(([k, v]) => `${k}: '${v}'`).join(', ') + ' }';
  return `// GENERATED per app — the component library reads these token NAMES; only the values change.
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        display: [${JSON.stringify(theme.fontDisplay).slice(1, -1).split(', ').map((f) => `'${f.replace(/'/g, '')}'`).join(', ')}],
        sans: [${JSON.stringify(theme.fontBody).slice(1, -1).split(', ').map((f) => `'${f.replace(/'/g, '')}'`).join(', ')}],
      },
      colors: {
        canvas: '${theme.canvas}',
        surface: '${theme.surface}',
        brandfg: '${theme.brandfg}',
        ink: ${scale(theme.ink)},
        brand: ${scale(theme.brand)},
        accent: ${scale(theme.accent)},
      },
      boxShadow: { soft: '${theme.shadow}' },
      borderRadius: { xl2: '${theme.radius}' },
    },
  },
  plugins: [],
}
`;
}

// scaffoldTheme(files, tokens) — write the per-app tailwind.config.js into the file set.
export function scaffoldTheme(files, tokens) {
  const out = { ...(files || {}) };
  out['tailwind.config.js'] = tailwindConfig(themeFor(tokens));
  return out;
}
