// THE THEME IS AUTHORED, NOT PICKED FROM A LIST (owner's call, 2026-08-20).
//
// Until this, `design_schema` took `theme` — one of a 100-name shortlist drawn
// from a 500-row registry — and every colour on the site came from a palette a
// person wrote months earlier, for nobody in particular. The owner's direction is
// the same one that killed the families: "have the model make its own theme".
//
// WHAT THE MODEL AUTHORS IS THREE COLOURS PER MODE, AND THAT IS THE WHOLE POINT.
// A theme is 31 colour tokens plus 17 style axes. The 500 hand-written themes did
// NOT hand-write 31 colours each — every one of them declares exactly `paper`,
// `ink` and `accent` per mode and lets `paletteFor` derive the other 28. Those
// derivations are where every legibility guarantee in this platform lives:
// `foregroundFor` picks a readable text colour for each surface, `fitState` drags
// a state colour up to 4.5:1, `separateFromAccent` stops a brand red reading as
// the destructive red, `worldBorderColor` keeps a divider darker than the ground
// it divides. Letting a model write those 31 values directly would throw all of
// it away for nothing anybody can see.
//
// So the seam is exactly where the registry's own data already put it: the model
// answers the three anchors, the engine derives the rest, and the derivation is
// untouched. `themeCss` has taken a theme OBJECT since it was written, so nothing
// downstream changes shape at all.
//
// HEX, NOT OKLCH, AND THAT WAS MEASURED. The internal format is an OKLCH triple,
// and a model writing `[0.48, 0.14, 28]` by hand is writing in a coordinate system
// it has far less fluency in than `#b44a2e` — and a transposed pair there
// (`[L, H, C]`) is a real, silent, in-range mistake. Round-tripping all 3,000
// seeds of the 500 themes through hex and back moves L or C by at most 0.058 and
// the resulting body-text contrast by at most 0.117, on ratios that run 10 to 20.
// Nothing that reaches a screen is lost either way — `oklchToRgb` clamps every
// shipped colour into sRGB regardless. And it is the notation the rest of this
// platform already speaks to the model: `site-tokens.mjs`'s value hint for a
// customer's own colour override is `#rrggbb`, and two colour notations in one
// design call is a way for them to get mixed up.
//
// Plain module with no I/O, like `site-plan.mjs` and `publish-pages.mjs`, so the
// whole decision is tested without a Worker, a model or a container.

import { contrast, paletteFor, rgbToOklch } from "./site-theme.mjs";

/* ------------------------------------------------------------------ shapes */

/** The three anchors, in the order the model fills them in. */
export const SEED_ROLES = Object.freeze(["paper", "ink", "accent"]);

/** Both halves of a theme. `dark` is optional — see `mirrorSeeds`. */
export const SEED_MODES = Object.freeze(["light", "dark"]);

/**
 * WHAT A NAME MAY CONTAIN, and this is a real injection rather than tidiness.
 *
 * `themeCss` emits `/* theme: ${name} — generated by … *\/` as the first line of
 * the stylesheet. A name containing the comment terminator closes that comment
 * early and everything after it becomes LIVE CSS on a customer's published site,
 * written by a model out of a brief that this codebase already treats as
 * attacker-controlled prose.
 *
 * An ALLOW-LIST rather than an escape, which is the rule every other value that
 * reaches a stylesheet here already lives under (`isColor`, `isLength`,
 * `routeSelectorOk`): the set of shapes a theme name can take is small enough to
 * list, so there is no escaping question to get wrong. Stripped rather than
 * refused, because a name is decoration on a palette that is otherwise perfectly
 * good and losing a whole theme over a stray character would be the tail wagging
 * the dog — but a name stripped to nothing falls back, or the comment reads
 * `/* theme:  — generated by …` and the reply sentence says the site is themed
 * "".
 */
// UNICODE LETTERS, NOT `A-Za-z`. An ASCII allow-list turns "Café Noir" into
// "Caf Noir" and a name in Greek, Cyrillic or Arabic into nothing at all —
// which is the exact failure the favicon initials already shipped once, where
// an `[A-Z]` filter gave a non-Latin business an empty mark. `\p{L}\p{M}\p{N}`
// admits every script and admits NO format character, so the bidi overrides
// stay out along with `*` and `/`: the comment injection this exists for is
// still closed.
//
// The em-dash is deliberately NOT admitted even though it is ordinary
// punctuation: `themeCss` does `.split("—")[0]` on a label, so a name carrying
// one would be silently cut in half on its way to the stylesheet.
const NAME_OK = /[^\p{L}\p{M}\p{N} '&.,()+-]/gu;
const MAX_NAME = 40;
export const DEFAULT_NAME = "Custom";

export function cleanThemeName(v) {
  if (typeof v !== "string") return DEFAULT_NAME;
  const out = v.replace(NAME_OK, " ").replace(/\s+/g, " ").trim().slice(0, MAX_NAME).trim();
  return out || DEFAULT_NAME;
}

/* ------------------------------------------------------------------ colour */

const HEX = /^#?([0-9a-f]{6})$/i;

/**
 * A hex colour to the engine's OKLCH triple, or null.
 *
 * SIX DIGITS ONLY. Three-digit shorthand is a convenience nobody needs here (the
 * model is writing one value, not typing it repeatedly) and the eight-digit form
 * carries ALPHA — which the contrast maths is not defined on, and which
 * `paletteFor` would silently drop. Refusing it is honest; accepting it and
 * dropping the alpha ships a colour the model did not choose.
 */
export function seedColor(v) {
  const m = HEX.exec(typeof v === "string" ? v.trim() : "");
  if (!m) return null;
  const n = m[1];
  const [r, g, b] = [0, 2, 4].map((i) => parseInt(n.slice(i, i + 2), 16) / 255);
  const [L, C, H] = rgbToOklch(r, g, b);
  // A pure grey has an undefined hue and `rgbToOklch` answers whatever the
  // floating-point noise says. Pinning it to 0 keeps two greys that should be
  // identical from deriving slightly different surfaces.
  return [L, C, C < 1e-4 ? 0 : H];
}

/* ------------------------------------------------------------------ mirror */

/**
 * THE DARK HALF, WHEN THE MODEL DID NOT WRITE ONE — and every number here was
 * measured off the 500 hand-written themes rather than chosen.
 *
 * Their light and dark halves are not two independent palettes: 391 of 500 are
 * EXACT hue mirrors, and the medians of the rest are tight enough to be a rule —
 * `dark.paper` is `light.ink` at L−0.07, `dark.ink` is `light.paper` at L−0.03,
 * `dark.accent` is `light.accent` at L+0.17 with the chroma unchanged (median
 * ratio 1.000).
 *
 * VERIFIED, NOT ASSUMED: applying this mirror to all 500 light halves and running
 * the real derivation gives a dark palette whose worst body text is 12.27:1, worst
 * muted 4.46:1 and worst button label 3.77:1 — every one clear of the floors
 * below, across every palette anybody has hand-written here.
 *
 * The accent LIFTS because a brand colour picked to sit on paper is too dark to
 * sit on a dark page; the paper and ink DARKEN slightly because a dark mode that
 * merely swaps the two is glarier than one anybody designs by hand.
 */
const MIRROR = Object.freeze({ paper: -0.07, ink: -0.03, accent: 0.17 });

/**
 * A NEUTRAL ACCENT MIRRORS LIKE INK, NOT LIKE AN ACCENT — and this is measured
 * too, not a special case bolted on.
 *
 * A brutalist theme's "brand colour" IS black. Lifting it by 0.17 gives a
 * near-black button on a near-black page: 1.4:1, which the floor below correctly
 * refuses. Both themes in the 500 that this hits (`manifesto`,
 * `brutalist-concrete`) had their dark accent hand-written, and both authors
 * FLIPPED it to near-white rather than lifting it.
 *
 * That is every author, without exception: all 11 themes with a near-neutral
 * accent put it on the dark side in light mode, all 11 moved it 0.45-0.87 in
 * dark, and all 11 land within 0.13 L of their own dark ink. So the rule is not
 * "lift further" — it is that a colourless accent is a value on the ink-to-paper
 * scale, and a value on that scale flips when the scale does.
 *
 * Its POSITION on that scale is preserved rather than its lightness: a mid-grey
 * accent stays mid, a near-black one becomes near-white.
 */
const NEUTRAL_CHROMA = 0.02;

const clamp = (v, lo, hi) => Math.min(hi, Math.max(lo, v));

export function mirrorSeeds(light) {
  const paper = [clamp(light.ink[0] + MIRROR.paper, 0, 1), light.ink[1], light.ink[2]];
  const ink = [clamp(light.paper[0] + MIRROR.ink, 0, 1), light.paper[1], light.paper[2]];

  let accentL;
  const span = light.paper[0] - light.ink[0];
  if (light.accent[1] < NEUTRAL_CHROMA && Math.abs(span) > 1e-6) {
    // Where the accent sits between ink and paper, kept across the flip. `span`
    // is guarded because a zero one would divide by zero — it cannot happen on a
    // theme that reaches here (the modes-not-swapped rule needs paper strictly
    // lighter than ink) but this runs BEFORE that check.
    const t = clamp((light.accent[0] - light.ink[0]) / span, 0, 1);
    accentL = ink[0] + t * (paper[0] - ink[0]);
  } else {
    accentL = light.accent[0] + MIRROR.accent;
  }
  return { paper, ink, accent: [clamp(accentL, 0, 1), light.accent[1], light.accent[2]] };
}

/* ------------------------------------------------------------------ floors */

/**
 * WHAT A PALETTE HAS TO CLEAR, measured across the 500 rather than taken from a
 * standards document.
 *
 * The floors are checked on the DERIVED palette — the 31 tokens that actually
 * ship — and never on the three seeds, because that is where the failure would
 * show. A seed-level rule ("ink must be dark") is a proxy; this asks the real
 * question.
 *
 * Every floor sits well under what 500 hand-written themes achieve, so it rejects
 * nothing anybody has designed and catches the palette a model can produce by
 * accident: grey text on a grey page.
 *
 *   body    hand-written min 10.67 (light) / 12.07 (dark) — floor 7
 *   muted   hand-written min  3.55 (light) /  4.42 (dark) — floor 3
 *   button  hand-written min  3.47 (light) /  4.60 (dark) — floor 3
 *
 * 3.0 AND NOT 4.5 FOR THE MUTED PAIR, deliberately and consistently with the rest
 * of the platform: `site-render.mjs`'s own contrast pass uses 3.0 for exactly this
 * reason — every theme's muted caption, placeholder and disabled control sits in
 * the 3-4.5 band ON PURPOSE, and a 4.5 floor would reject deliberate design. A
 * button label is large text, where 3:1 is the standard's own bar.
 */
export const FLOORS = Object.freeze([
  { fg: "foreground", bg: "background", min: 7, what: "body text" },
  { fg: "card-foreground", bg: "card", min: 7, what: "text on cards" },
  // THESE TWO NAMES MUST NOT BE PREFIXES OF EACH OTHER, and the first draft's
  // were: "quiet text" and "quiet text on the page". Two consequences, and the
  // second is the one that reaches a customer. A derived test asking whether the
  // report mentions a floor is satisfied by the WRONG entry, so one of them was
  // covered by nothing (found by mutation). And a refusal that says "quiet text
  // is 2.1:1" twice, about two different surfaces, is a message nobody can act
  // on. Asserted as a property, because the natural way to name a second variant
  // of something is to extend the first one's name.
  { fg: "muted-foreground", bg: "muted", min: 3, what: "quiet text on a card" },
  { fg: "muted-foreground", bg: "background", min: 3, what: "quiet text on the page" },
  { fg: "primary-foreground", bg: "primary", min: 3, what: "button labels" },
  // THE ONE NO LABEL CHECK CAN SEE, and it got through the first draft. A
  // near-white accent gives a button whose LABEL is perfectly legible —
  // `foregroundFor` picks the dark ink for it and reports 15:1 — while the
  // button itself is the same colour as the page and the visitor cannot find
  // the thing they are meant to press. Measured: `#f7f4ee` on `#ffffff` is
  // 1.10:1 against the page and 15.4:1 on the label.
  //
  // 1.5 IS DELIBERATELY VERY LOW, because a button is not text: it carries a
  // border, a shadow and a shape, and a quiet ghost button on near-white paper
  // is a real design rather than a fault. The lowest of the 500 hand-written
  // themes is 1.98, so this rejects none of them and catches only the case
  // where the accent IS the paper.
  { fg: "primary", bg: "background", min: 1.5, what: "the button against the page" },
]);

/**
 * Everything wrong with a theme's derived palette, as sentences. `[]` is good.
 *
 * DRIVES THE REAL `paletteFor` rather than restating what it does. A second
 * opinion about how a surface is derived is a second thing to keep in step, and
 * the direction it drifts in is a check that passes a palette the site then
 * renders illegibly.
 */
export function paletteProblems(theme) {
  const out = [];
  for (const mode of SEED_MODES) {
    let p;
    try {
      p = paletteFor(theme, mode);
    } catch {
      out.push("the " + mode + " palette could not be worked out");
      continue;
    }
    for (const f of FLOORS) {
      const c = contrast(p[f.fg], p[f.bg]);
      if (!(c >= f.min)) {
        out.push(f.what + " in " + mode + " mode is " + c.toFixed(1) + ":1, under " + f.min + ":1");
      }
    }
  }
  return out;
}

/* -------------------------------------------------------------- normaliser */

/**
 * A model's answer to the seeds field, as a theme object the engine can use —
 * or null, with the reason, when it cannot be used.
 *
 * REFUSES RATHER THAN REPAIRS. Everywhere else in this codebase a colour that
 * cannot be read is dropped and the rest of the change goes through, because
 * those changes are one token each. A theme is not one token: nudging a bad seed
 * until it clears a floor produces a palette nobody chose, on a site that then
 * reports the theme it asked for. The caller falls back to a known-good theme and
 * SAYS SO, which is the same bargain `resolveTheme` already made with an unknown
 * name.
 *
 * The reason travels because four different failures — no seeds at all, an
 * unreadable colour, swapped modes, an illegible palette — need four different
 * responses, and this repo has paid several times over for a refusal that could
 * only say one thing.
 */
export function normalizeSeeds(raw) {
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) {
    return { theme: null, why: "no seeds" };
  }

  // DECLARED BEFORE THE CLOSURE THAT WRITES IT. `read` is only ever CALLED after
  // this line, so the other order runs today — and it is the exact shape of the
  // `vidRefN` and `du.id` failures this repo has shipped twice: a name read from
  // a closure whose declaration sits below it, correct until somebody moves a
  // call.
  const bad = [];

  const read = (block, where) => {
    if (!block || typeof block !== "object" || Array.isArray(block)) return null;
    const out = {};
    for (const role of SEED_ROLES) {
      const c = seedColor(block[role]);
      if (!c) {
        bad.push(where + " " + role + " is not a #rrggbb colour");
        return null;
      }
      out[role] = c;
    }
    return out;
  };

  const light = read(raw, "light");
  if (!light) return { theme: null, why: bad[0] || "the light colours are missing" };

  // `dark` is OPTIONAL and a HALF-WRITTEN one is refused rather than completed.
  // Filling in the two roles a model did name from the mirror while keeping the
  // third is a palette assembled from two different intents, which is exactly the
  // shape that produces an accent nobody can read on a page nobody chose.
  let dark = null;
  if (raw.dark != null) {
    dark = read(raw.dark, "dark");
    if (!dark) return { theme: null, why: bad[0] || "the dark colours are incomplete" };
  }
  const mirrored = !dark;
  if (!dark) dark = mirrorSeeds(light);

  // THE ONE THING CONTRAST CANNOT SEE. A theme whose modes are swapped is
  // perfectly legible in both — and renders dark when the visitor asked for
  // light, and light when they asked for dark. `SITE_MODE` stamps the class; the
  // seeds have to mean what they say.
  if (!(light.paper[0] > light.ink[0])) {
    return { theme: null, why: "the light mode's paper is not lighter than its ink" };
  }
  if (!(dark.paper[0] < dark.ink[0])) {
    return { theme: null, why: "the dark mode's paper is not darker than its ink" };
  }

  const theme = { label: cleanThemeName(raw.name), light, dark };
  const problems = paletteProblems(theme);
  if (problems.length) return { theme: null, why: problems[0], problems };

  return { theme, why: "", mirrored };
}

/* ------------------------------------------------------------------ prompt */

const HEX_HINT = 'A hex colour, "#rrggbb".';

const MODE_FIELDS = () => ({
  paper: { type: "string", description: HEX_HINT + " The page itself." },
  ink: { type: "string", description: HEX_HINT + " Body text." },
  accent: { type: "string", description: HEX_HINT + " The brand colour — buttons, links, the one thing that stands out." },
});

/**
 * THE FIELD, as `design_schema` carries it.
 *
 * THREE COLOURS, NOT THIRTY-ONE, and the description says why in the model's own
 * terms: everything else is worked out from these. A field that merely asked for
 * "the colours" invites a model to reach for the thirty-one it can see in the
 * template, and every one it wrote by hand would bypass a legibility guarantee.
 *
 * THE ORDER IS THE INSTRUCTION, the same property `PLAN_KEYS` turns on: `name`
 * first makes the model commit to what the site FEELS like before it picks a
 * colour, which is the order a person works in and produces a palette that hangs
 * together rather than three colours chosen one at a time.
 *
 * `dark` IS LAST AND OPTIONAL because the mirror is measured and safe (see
 * `mirrorSeeds`), so most sites should not spend tokens on it — and a model that
 * has a real reason for a different dark mode can still say so.
 */
export const SEEDS_FIELD = Object.freeze({
  type: "object",
  description:
    "The site's own palette, authored for THIS business. Three colours; everything else — cards, borders, " +
    "inputs, quiet text, the success and danger colours — is worked out from them, so do not try to name those. " +
    "Pick for the trade and its mood, not for novelty: most businesses want a quiet, nearly-neutral paper and " +
    "one accent that means something to them. Keep the paper light and the ink dark; the contrast between them " +
    "is what the whole site's legibility rests on.",
  properties: {
    name: { type: "string", description: "Two or three words for this palette, e.g. \"Warm Brick\" or \"Coastal Fog\". Shown to the customer." },
    ...MODE_FIELDS(),
    dark: {
      type: "object",
      description:
        "OPTIONAL. Leave it out unless this site needs a dark mode that is not simply the light one inverted — " +
        "a good dark palette is derived from the three colours above automatically.",
      properties: MODE_FIELDS(),
      required: [...SEED_ROLES],
    },
  },
  required: ["name", ...SEED_ROLES],
});
